const WORD_SETS = {
  elem: [
    {en:'apple',ko:'사과'},{en:'banana',ko:'바나나'},{en:'cat',ko:'고양이'},{en:'dog',ko:'개'},{en:'bird',ko:'새'},
    {en:'fish',ko:'물고기'},{en:'book',ko:'책'},{en:'pen',ko:'펜'},{en:'bag',ko:'가방'},{en:'chair',ko:'의자'},
    {en:'table',ko:'탁자'},{en:'bed',ko:'침대'},{en:'cup',ko:'컵'},{en:'milk',ko:'우유'},{en:'water',ko:'물'},
    {en:'bread',ko:'빵'},{en:'rice',ko:'쌀, 밥'},{en:'egg',ko:'달걀'},{en:'school',ko:'학교'},{en:'teacher',ko:'선생님'},
    {en:'student',ko:'학생'},{en:'friend',ko:'친구'},{en:'family',ko:'가족'},{en:'mother',ko:'어머니'},{en:'father',ko:'아버지'},
    {en:'sister',ko:'여자 형제'},{en:'brother',ko:'남자 형제'},{en:'house',ko:'집'},{en:'room',ko:'방'},{en:'door',ko:'문'},
    {en:'window',ko:'창문'},{en:'car',ko:'자동차'},{en:'bus',ko:'버스'},{en:'train',ko:'기차'},{en:'bike',ko:'자전거'},
    {en:'street',ko:'거리'},{en:'park',ko:'공원'},{en:'tree',ko:'나무'},{en:'flower',ko:'꽃'},{en:'sun',ko:'태양'},
    {en:'moon',ko:'달'},{en:'star',ko:'별'},{en:'sky',ko:'하늘'},{en:'rain',ko:'비'},{en:'snow',ko:'눈'},
    {en:'cloud',ko:'구름'},{en:'day',ko:'낮, 하루'},{en:'night',ko:'밤'},{en:'morning',ko:'아침'},{en:'evening',ko:'저녁'},
    {en:'happy',ko:'행복한'},{en:'sad',ko:'슬픈'},{en:'big',ko:'큰'},{en:'small',ko:'작은'},{en:'long',ko:'긴'},
    {en:'short',ko:'짧은'},{en:'hot',ko:'뜨거운'},{en:'cold',ko:'차가운'},{en:'good',ko:'좋은'},{en:'bad',ko:'나쁜'},
    {en:'up',ko:'위로'},{en:'down',ko:'아래로'},{en:'left',ko:'왼쪽'},{en:'right',ko:'오른쪽'},{en:'run',ko:'달리다'},
    {en:'walk',ko:'걷다'},{en:'jump',ko:'점프하다'},{en:'sit',ko:'앉다'},{en:'stand',ko:'서다'},{en:'eat',ko:'먹다'},
    {en:'drink',ko:'마시다'},{en:'read',ko:'읽다'},{en:'write',ko:'쓰다'},{en:'play',ko:'놀다, 연주하다'},{en:'sing',ko:'노래하다'},
    {en:'dance',ko:'춤추다'},{en:'open',ko:'열다'},{en:'close',ko:'닫다'},{en:'come',ko:'오다'},{en:'go',ko:'가다'},
    {en:'see',ko:'보다'},{en:'hear',ko:'듣다'},{en:'talk',ko:'말하다'},{en:'listen',ko:'듣다'},{en:'give',ko:'주다'},
    {en:'take',ko:'가져가다'},{en:'make',ko:'만들다'},{en:'find',ko:'찾다'},{en:'help',ko:'돕다'},{en:'love',ko:'사랑하다'},
    {en:'like',ko:'좋아하다'},{en:'want',ko:'원하다'},{en:'need',ko:'필요하다'},{en:'wash',ko:'씻다'},{en:'clean',ko:'청소하다'},
    {en:'stop',ko:'멈추다'},{en:'start',ko:'시작하다'},{en:'laugh',ko:'웃다'},{en:'cry',ko:'울다'},{en:'sleep',ko:'자다'}
  ],
  mid: [
    {en:'ability',ko:'능력'},{en:'accident',ko:'사고'},{en:'achieve',ko:'성취하다'},{en:'active',ko:'활동적인'},{en:'advice',ko:'조언'},
    {en:'afford',ko:'~할 여유가 있다'},{en:'agree',ko:'동의하다'},{en:'allow',ko:'허락하다'},{en:'almost',ko:'거의'},{en:'alone',ko:'혼자인'},
    {en:'along',ko:'~을 따라'},{en:'already',ko:'이미'},{en:'although',ko:'비록 ~일지라도'},{en:'amount',ko:'양, 액수'},{en:'ancient',ko:'고대의'},
    {en:'announce',ko:'발표하다'},{en:'appear',ko:'나타나다'},{en:'apply',ko:'신청하다, 적용하다'},{en:'area',ko:'지역, 영역'},{en:'argue',ko:'논쟁하다'},
    {en:'arrange',ko:'정리하다, 배열하다'},{en:'arrive',ko:'도착하다'},{en:'article',ko:'기사, 물품'},{en:'attend',ko:'참석하다'},{en:'avoid',ko:'피하다'},
    {en:'balance',ko:'균형'},{en:'behavior',ko:'행동'},{en:'belong',ko:'속하다'},{en:'benefit',ko:'이익, 혜택'},{en:'beyond',ko:'~을 넘어'},
    {en:'birth',ko:'탄생'},{en:'blame',ko:'비난하다'},{en:'block',ko:'막다, 블록'},{en:'blood',ko:'피'},{en:'board',ko:'판, 탑승하다'},
    {en:'borrow',ko:'빌리다'},{en:'brave',ko:'용감한'},{en:'breathe',ko:'숨쉬다'},{en:'bridge',ko:'다리'},{en:'bright',ko:'밝은'},
    {en:'bring',ko:'가져오다'},{en:'build',ko:'짓다'},{en:'burn',ko:'태우다'},{en:'business',ko:'사업'},{en:'busy',ko:'바쁜'},
    {en:'captain',ko:'선장, 주장'},{en:'carry',ko:'나르다'},{en:'cause',ko:'원인, ~을 일으키다'},{en:'century',ko:'세기'},{en:'certain',ko:'확실한'},
    {en:'chance',ko:'기회'},{en:'change',ko:'변화, 바꾸다'},{en:'character',ko:'성격, 등장인물'},{en:'check',ko:'확인하다, 수표'},{en:'choose',ko:'선택하다'},
    {en:'clear',ko:'명확한, 깨끗한'},{en:'climb',ko:'오르다'},{en:'close',ko:'닫다, 가까운'},{en:'cloud',ko:'구름'},{en:'collect',ko:'모으다'},
    {en:'common',ko:'흔한'},{en:'compare',ko:'비교하다'},{en:'complete',ko:'완성하다'},{en:'condition',ko:'상태, 조건'},{en:'connect',ko:'연결하다'},
    {en:'contain',ko:'포함하다'},{en:'continue',ko:'계속하다'},{en:'control',ko:'통제하다'},{en:'copy',ko:'복사하다'},{en:'corner',ko:'모퉁이'},
    {en:'correct',ko:'올바른, 수정하다'},{en:'cost',ko:'비용'},{en:'count',ko:'세다'},{en:'country',ko:'나라, 시골'},{en:'cover',ko:'덮다'},
    {en:'create',ko:'창조하다'},{en:'culture',ko:'문화'},{en:'customer',ko:'손님, 고객'},{en:'daily',ko:'매일의'},{en:'damage',ko:'손해, 손상시키다'},
    {en:'dangerous',ko:'위험한'},{en:'decide',ko:'결정하다'},{en:'decrease',ko:'줄이다'},{en:'deep',ko:'깊은'},{en:'deliver',ko:'배달하다'},
    {en:'depend',ko:'의존하다'},{en:'describe',ko:'묘사하다'},{en:'design',ko:'설계하다'},{en:'develop',ko:'발전하다'},{en:'difference',ko:'차이'},
    {en:'difficult',ko:'어려운'},{en:'direction',ko:'방향'},{en:'disappear',ko:'사라지다'},{en:'discover',ko:'발견하다'},{en:'distance',ko:'거리'},
    {en:'divide',ko:'나누다'},{en:'doctor',ko:'의사'},{en:'double',ko:'두 배의'},{en:'draw',ko:'그리다'},{en:'dream',ko:'꿈, 꿈꾸다'}
  ],
  high: [
    {en:'abandon',ko:'버리다, 포기하다'},{en:'abstract',ko:'추상적인'},{en:'abuse',ko:'남용하다, 학대하다'},{en:'accompany',ko:'동행하다'},{en:'accomplish',ko:'이루다'},
    {en:'accumulate',ko:'축적하다'},{en:'accurate',ko:'정확한'},{en:'adapt',ko:'적응하다'},{en:'adequate',ko:'충분한'},{en:'adjust',ko:'조정하다'},
    {en:'advocate',ko:'옹호하다'},{en:'alter',ko:'변경하다'},{en:'ambiguous',ko:'애매한'},{en:'analyze',ko:'분석하다'},{en:'anticipate',ko:'예상하다'},
    {en:'apparent',ko:'분명한'},{en:'appropriate',ko:'적절한'},{en:'approve',ko:'승인하다'},{en:'artificial',ko:'인공의'},{en:'assign',ko:'할당하다'},
    {en:'assume',ko:'가정하다'},{en:'assure',ko:'보장하다'},{en:'attach',ko:'붙이다'},{en:'attempt',ko:'시도하다'},{en:'attain',ko:'달성하다'},
    {en:'aware',ko:'알고 있는'},{en:'barrier',ko:'장벽'},{en:'benefit',ko:'이익, 혜택'},{en:'burden',ko:'부담'},{en:'calculate',ko:'계산하다'},
    {en:'candidate',ko:'후보자'},{en:'capacity',ko:'수용력, 능력'},{en:'capture',ko:'붙잡다'},{en:'cease',ko:'중단하다'},{en:'challenge',ko:'도전'},
    {en:'circumstance',ko:'상황'},{en:'collapse',ko:'붕괴하다'},{en:'colleague',ko:'동료'},{en:'commit',ko:'저지르다, 헌신하다'},{en:'compensate',ko:'보상하다'},
    {en:'compile',ko:'편집하다'},{en:'complain',ko:'불평하다'},{en:'component',ko:'구성 요소'},{en:'comprise',ko:'구성하다'},{en:'concentrate',ko:'집중하다'},
    {en:'conclude',ko:'결론짓다'},{en:'concrete',ko:'구체적인'},{en:'conduct',ko:'수행하다, 행동'},{en:'confirm',ko:'확인하다'},{en:'conflict',ko:'갈등, 충돌'},
    {en:'conform',ko:'순응하다'},{en:'consequence',ko:'결과'},{en:'considerable',ko:'상당한'},{en:'consist',ko:'이루어져 있다'},{en:'constant',ko:'지속적인'},
    {en:'construct',ko:'건설하다'},{en:'consume',ko:'소비하다'},{en:'contribute',ko:'기여하다'},{en:'controversy',ko:'논란'},{en:'convenient',ko:'편리한'},
    {en:'convert',ko:'전환하다'},{en:'cooperate',ko:'협력하다'},{en:'cope',ko:'대처하다'},{en:'corporate',ko:'기업의'},{en:'correspond',ko:'일치하다'},
    {en:'crucial',ko:'결정적인'},{en:'cultivate',ko:'경작하다, 개발하다'},{en:'dedicate',ko:'헌신하다'},{en:'defend',ko:'방어하다'},{en:'demonstrate',ko:'시연하다, 입증하다'},
    {en:'deny',ko:'부인하다'},{en:'depart',ko:'떠나다'},{en:'depress',ko:'우울하게 하다'},{en:'derive',ko:'끌어내다, 유래하다'},{en:'deserve',ko:'~할 가치가 있다'},
    {en:'detect',ko:'감지하다'},{en:'determine',ko:'결정하다'},{en:'diminish',ko:'줄어들다'},{en:'discipline',ko:'규율, 훈련'},{en:'distinguish',ko:'구별하다'},
    {en:'distribute',ko:'분배하다'},{en:'domestic',ko:'국내의, 가정의'},{en:'dominate',ko:'지배하다'},{en:'eliminate',ko:'제거하다'},{en:'emerge',ko:'나타나다'},
    {en:'emphasize',ko:'강조하다'},{en:'enable',ko:'가능하게 하다'},{en:'encounter',ko:'마주치다'},{en:'enhance',ko:'향상시키다'},{en:'ensure',ko:'보장하다'},
    {en:'equivalent',ko:'동등한'},{en:'establish',ko:'설립하다'},{en:'evaluate',ko:'평가하다'},{en:'evolve',ko:'진화하다'},{en:'exceed',ko:'초과하다'},
    {en:'exclude',ko:'제외하다'},{en:'expand',ko:'확장하다'},{en:'exploit',ko:'이용하다, 착취하다'},{en:'expose',ko:'드러내다'},{en:'extend',ko:'연장하다'}
  ],
  uni: [
    {en:'abolish',ko:'폐지하다'},{en:'abrupt',ko:'갑작스러운'},{en:'abundant',ko:'풍부한'},{en:'accessible',ko:'접근 가능한'},{en:'accommodate',ko:'수용하다, 편의를 제공하다'},
    {en:'accompany',ko:'동반하다'},{en:'accomplish',ko:'완수하다'},{en:'accumulate',ko:'축적하다'},{en:'acquisition',ko:'습득, 취득'},{en:'adjacent',ko:'인접한'},
    {en:'advocate',ko:'옹호하다'},{en:'aggregate',ko:'모으다, 총합'},{en:'allocate',ko:'할당하다'},{en:'alter',ko:'변경하다'},{en:'ambiguous',ko:'모호한'},
    {en:'analogy',ko:'유사, 비유'},{en:'analyze',ko:'분석하다'},{en:'anomaly',ko:'변칙, 예외'},{en:'apparent',ko:'명백한'},{en:'applicable',ko:'적용 가능한'},
    {en:'appreciate',ko:'감사하다, 감상하다'},{en:'arbitrary',ko:'임의의, 독단적인'},{en:'aspect',ko:'측면'},{en:'assemble',ko:'모으다, 조립하다'},{en:'assess',ko:'평가하다'},
    {en:'assign',ko:'부과하다, 할당하다'},{en:'assume',ko:'가정하다'},{en:'attain',ko:'달성하다'},{en:'attribute',ko:'~의 결과로 보다'},{en:'authorize',ko:'승인하다'},
    {en:'autonomous',ko:'자율적인'},{en:'behalf',ko:'이익, 편'},{en:'beneficial',ko:'유익한'},{en:'bias',ko:'편견'},{en:'bulk',ko:'대부분, 큰 규모'},
    {en:'capacity',ko:'용량, 능력'},{en:'cease',ko:'중단하다'},{en:'coherent',ko:'일관된'},{en:'coincide',ko:'동시에 일어나다'},{en:'collapse',ko:'붕괴하다'},
    {en:'colleague',ko:'동료'},{en:'commence',ko:'시작하다'},{en:'commodity',ko:'상품'},{en:'compatible',ko:'양립 가능한'},{en:'compile',ko:'편집하다'},
    {en:'complement',ko:'보완하다'},{en:'comprehensive',ko:'종합적인'},{en:'comprise',ko:'포함하다, 구성하다'},{en:'compulsory',ko:'의무적인'},{en:'conceive',ko:'상상하다, 생각하다'},
    {en:'concurrent',ko:'동시에 발생하는'},{en:'confer',ko:'상의하다, 수여하다'},{en:'confine',ko:'제한하다'},{en:'confirm',ko:'확인하다'},{en:'conform',ko:'따르다'},
    {en:'consent',ko:'동의하다'},{en:'consequent',ko:'결과로서 일어나는'},{en:'considerable',ko:'상당한'},{en:'constitute',ko:'구성하다'},{en:'constrain',ko:'강요하다'},
    {en:'construct',ko:'건설하다'},{en:'consult',ko:'상담하다'},{en:'consume',ko:'소비하다'},{en:'contemporary',ko:'동시대의'},{en:'contradict',ko:'반박하다'},
    {en:'contrary',ko:'반대의'},{en:'controversial',ko:'논란이 되는'},{en:'convene',ko:'소집하다'},{en:'converse',ko:'대화하다, 반대의'},{en:'convert',ko:'전환하다'},
    {en:'cooperate',ko:'협력하다'},{en:'coordinate',ko:'조정하다'},{en:'core',ko:'핵심'},{en:'correspond',ko:'일치하다, 해당하다'},{en:'crucial',ko:'결정적인'},
    {en:'currency',ko:'통화, 유통'},{en:'deduce',ko:'추론하다'},{en:'demonstrate',ko:'입증하다'},{en:'denote',ko:'나타내다'},{en:'derive',ko:'끌어내다, 유래하다'},
    {en:'detect',ko:'감지하다'},{en:'deviate',ko:'벗어나다'},{en:'differentiate',ko:'구별하다'},{en:'dimension',ko:'차원, 규모'},{en:'diminish',ko:'감소하다'},
    {en:'discrete',ko:'별개의'},{en:'discriminate',ko:'차별하다, 구별하다'},{en:'dispose',ko:'처리하다'},{en:'distinct',ko:'뚜렷한'},{en:'distort',ko:'왜곡하다'},
    {en:'distribute',ko:'배포하다'},{en:'diverse',ko:'다양한'},{en:'document',ko:'기록하다'},{en:'domain',ko:'영역'},{en:'domestic',ko:'국내의'},
    {en:'dominant',ko:'지배적인'},{en:'duration',ko:'지속 기간'},{en:'dynamic',ko:'역동적인'},{en:'eliminate',ko:'제거하다'},{en:'empirical',ko:'경험에 의한'}
  ],
  gre: [
    {en:'abate',ko:'줄이다, 완화하다'},{en:'aberrant',ko:'비정상적인'},{en:'abjure',ko:'(신념·권리 등을) 포기하다'},{en:'abrogate',ko:'폐지하다'},{en:'abstruse',ko:'난해한'},
    {en:'accede',ko:'동의하다'},{en:'acerbic',ko:'신랄한'},{en:'acquiesce',ko:'묵인하다'},{en:'adroit',ko:'능숙한'},{en:'aesthete',ko:'심미안이 있는 사람'},
    {en:'alacrity',ko:'민첩함, 선뜻 함'},{en:'amalgamate',ko:'합병하다'},{en:'ameliorate',ko:'개선하다'},{en:'anachronism',ko:'시대착오'},{en:'anathema',ko:'절대 반대, 저주받은 것'},
    {en:'anomalous',ko:'이례적인'},{en:'antipathy',ko:'반감'},{en:'apocryphal',ko:'진위가 의심스러운'},{en:'approbation',ko:'승인, 칭찬'},{en:'arcane',ko:'비밀의, 난해한'},
    {en:'ardor',ko:'열정'},{en:'artifice',ko:'책략, 기교'},{en:'asperity',ko:'거침, 가혹함'},{en:'assiduous',ko:'부지런한'},{en:'attenuate',ko:'약화시키다'},
    {en:'austere',ko:'엄격한, 금욕적인'},{en:'avarice',ko:'탐욕'},{en:'baleful',ko:'해로운, 위협적인'},{en:'belie',ko:'모순되다, 거짓임을 보여주다'},{en:'bellicose',ko:'호전적인'},
    {en:'benignant',ko:'친절한, 유익한'},{en:'bombastic',ko:'과장된'},{en:'bucolic',ko:'전원적인'},{en:'cadge',ko:'빌붙다'},{en:'calumny',ko:'중상, 비방'},
    {en:'captious',ko:'트집 잡는'},{en:'castigate',ko:'혹평하다, 징계하다'},{en:'censure',ko:'비난하다'},{en:'chicanery',ko:'속임수'},{en:'churlish',ko:'무례한'},
    {en:'cogent',ko:'설득력 있는'},{en:'commensurate',ko:'비례하는'},{en:'complaisant',ko:'선뜻 남을 따르는'},{en:'concomitant',ko:'수반되는'},{en:'confound',ko:'혼동하다, 당황하게 하다'},
    {en:'connoisseur',ko:'감정가, 전문가'},{en:'consummate',ko:'완전한, 완벽하게 하다'},{en:'contrite',ko:'뉘우치는'},{en:'contumacious',ko:'고집 센'},{en:'copious',ko:'풍부한'},
    {en:'corpulent',ko:'뚱뚱한'},{en:'cosset',ko:'응석받이로 키우다'},{en:'craven',ko:'비겁한'},{en:'credulous',ko:'잘 속는'},{en:'cursory',ko:'대충 하는'},
    {en:'dearth',ko:'부족'},{en:'debacle',ko:'붕괴, 대실패'},{en:'decorum',ko:'예의'},{en:'deference',ko:'존중, 복종'},{en:'deleterious',ko:'해로운'},
    {en:'demagogue',ko:'선동 정치가'},{en:'demur',ko:'이의를 제기하다'},{en:'denigrate',ko:'폄하하다'},{en:'deride',ko:'조롱하다'},{en:'desultory',ko:'산만한, 두서없는'},
    {en:'diaphanous',ko:'아주 얇은, 비치는'},{en:'didactic',ko:'교훈적인'},{en:'diffident',ko:'소심한, 자신 없는'},{en:'dilatory',ko:'지연하는'},{en:'disabuse',ko:'오해를 바로잡아 주다'},
    {en:'discomfit',ko:'당황하게 하다'},{en:'disparate',ko:'본질적으로 다른'},{en:'dissemble',ko:'(진실을) 숨기다'},{en:'dissonance',ko:'불일치, 부조화'},{en:'distend',ko:'부풀리다'},
    {en:'divest',ko:'빼앗다, 박탈하다'},{en:'dogmatic',ko:'독단적인'},{en:'duress',ko:'협박, 강요'},{en:'ebullient',ko:'열정적인'},{en:'effrontery',ko:'뻔뻔스러움'},
    {en:'egregious',ko:'지독한'},{en:'elegiac',ko:'애가의, 슬픈'},{en:'elicit',ko:'끌어내다'},{en:'emollient',ko:'완화제, 진정시키는'},{en:'enervate',ko:'약화시키다'},
    {en:'engender',ko:'낳다, 발생시키다'},{en:'ennui',ko:'권태'},{en:'enshrine',ko:'신성하게 보관하다'},{en:'ephemeral',ko:'단명하는'},{en:'epicure',ko:'미식가'},
    {en:'equanimity',ko:'침착, 평정'},{en:'equivocate',ko:'얼버무리다'},{en:'erudite',ko:'박식한'},{en:'eschew',ko:'피하다'},{en:'espouse',ko:'지지하다'},
    {en:'estimable',ko:'존경할 만한'},{en:'eulogize',ko:'찬양하다'},{en:'exacerbate',ko:'악화시키다'},{en:'excoriate',ko:'혹평하다'},{en:'exigent',ko:'긴급한, 절박한'}
  ]
};

const REVIEW_DATA = {
  elem: {
    'apple': { example: "I eat an apple every day.", translation: "나는 매일 사과를 먹어요.", mnemonic: "동그랗고 빨간 **애플**! 아삭! 하고 베어 물어요." },
    'banana': { example: "Monkeys love to eat bananas.", translation: "원숭이들은 바나나 먹는 것을 좋아해요.", mnemonic: "길고 노란 **바나나**! 껍질을 쏙 벗겨 먹어요." },
    'cat': { example: "The cat is sleeping on the sofa.", translation: "고양이가 소파에서 자고 있어요.", mnemonic: "\"야옹\"하고 우는 귀여운 **캣**!" },
    'dog': { example: "My dog wags its tail when it's happy.", translation: "우리 집 개는 기쁠 때 꼬리를 흔들어요.", mnemonic: "\"멍멍\" 짖는 우리의 친구 **도그**!" },
    'bird': { example: "A small bird is singing on the tree.", translation: "작은 새가 나무 위에서 노래하고 있어요.", mnemonic: "하늘을 훨훨 나는 **버드**!" },
    'fish': { example: "There are many colorful fish in the sea.", translation: "바다에는 다채로운 물고기들이 많이 있어요.", mnemonic: "물속에서 헤엄치는 **피쉬**! 뻐끔뻐끔!" },
    'book': { example: "I like to read a book before bed.", translation: "저는 자기 전에 책 읽는 것을 좋아해요.", mnemonic: "재미있는 이야기가 가득한 **북**! 한 장씩 넘겨봐요." },
    'pen': { example: "Can I borrow your pen?", translation: "펜 좀 빌릴 수 있을까요?", mnemonic: "글씨를 또박또박 쓰는 **펜**!" },
    'bag': { example: "I put my books in my school bag.", translation: "나는 책들을 내 책가방에 넣어요.", mnemonic: "어깨에 메는 나의 **백**!" },
    'chair': { example: "Please sit on this chair.", translation: "이 의자에 앉으세요.", mnemonic: "편안하게 앉는 **체어**!" },
    'table': { example: "The food is on the table.", translation: "음식이 탁자 위에 있어요.", mnemonic: "네모난 **테이블** 위에 맛있는 음식이!" },
    'bed': { example: "It's time to go to bed.", translation: "잠자리에 들 시간이에요.", mnemonic: "포근한 이불이 있는 나의 **베드**!" },
    'cup': { example: "I drink water from a cup.", translation: "나는 컵으로 물을 마셔요.", mnemonic: "손잡이가 달린 동그란 **컵**!" },
    'milk': { example: "Drinking milk makes you strong.", translation: "우유를 마시면 튼튼해져요.", mnemonic: "하얗고 고소한 **밀크**! 쑥쑥 커요!" },
    'water': { example: "Please give me a glass of water.", translation: "물 한 잔만 주세요.", mnemonic: "목마를 때 마시는 시원한 **워터**!" },
    'bread': { example: "I eat bread with jam for breakfast.", translation: "나는 아침으로 빵과 잼을 먹어요.", mnemonic: "갓 구워서 따끈따끈한 **브레드**!" },
    'rice': { example: "We eat rice for lunch.", translation: "우리는 점심으로 밥을 먹어요.", mnemonic: "밥솥에서 김이 모락모락 나는 **라이스**!" },
    'egg': { example: "I can cook an egg.", translation: "나는 달걀을 요리할 수 있어요.", mnemonic: "동그란 **에그**를 톡! 깨서 프라이를 만들어요." },
    'school': { example: "I go to school every morning.", translation: "나는 매일 아침 학교에 가요.", mnemonic: "친구들과 공부하는 즐거운 **스쿨**!" },
    'teacher': { example: "My teacher is very kind.", translation: "우리 선생님은 매우 친절하세요.", mnemonic: "우리를 가르쳐주시는 고마운 **티처**!" },
    'student': { example: "I am a student.", translation: "저는 학생입니다.", mnemonic: "열심히 공부하는 우리는 **스튜던트**!" },
    'friend': { example: "He is my best friend.", translation: "그는 나의 가장 친한 친구예요.", mnemonic: "나랑 같이 노는 소중한 **프렌드**!" },
    'family': { example: "I love my family.", translation: "저는 우리 가족을 사랑해요.", mnemonic: "엄마, 아빠, 나, 우리 모두 **패밀리**!" },
    'mother': { example: "My mother reads me a story.", translation: "엄마는 나에게 이야기를 읽어줘요.", mnemonic: "나를 사랑해주시는 우리 **마더**!" },
    'father': { example: "My father is tall.", translation: "우리 아빠는 키가 크세요.", mnemonic: "든든한 우리 아빠, **파더**!" },
    'sister': { example: "I have an older sister.", translation: "나는 언니(누나)가 한 명 있어요.", mnemonic: "나랑 닮은 여자 형제, **시스터**!" },
    'brother': { example: "My brother plays soccer.", translation: "내 남동생(형/오빠)은 축구를 해요.", mnemonic: "씩씩한 남자 형제, **브라더**!" },
    'house': { example: "This is my house.", translation: "여기가 우리 집이에요.", mnemonic: "따뜻한 우리 집, 마이 **하우스**!" },
    'room': { example: "I clean my room on weekends.", translation: "나는 주말에 내 방을 청소해요.", mnemonic: "내 침대와 책상이 있는 나의 **룸**!" },
    'door': { example: "Please close the door.", translation: "문 좀 닫아주세요.", mnemonic: "방으로 들어가는 **도어**를 열어요." },
    'window': { example: "Open the window to get some fresh air.", translation: "신선한 공기를 마시게 창문을 여세요.", mnemonic: "네모난 **윈도우** 밖으로 풍경이 보여요." },
    'car': { example: "My dad drives a car.", translation: "아빠는 자동차를 운전하세요.", mnemonic: "\"부릉부릉\" 달리는 멋진 **카**!" },
    'bus': { example: "I take a bus to school.", translation: "나는 버스를 타고 학교에 가요.", mnemonic: "많은 사람이 함께 타는 **버스**!" },
    'train': { example: "The train is very fast.", translation: "기차는 매우 빨라요.", mnemonic: "\"칙칙폭폭\" 긴 **트레인**!" },
    'bike': { example: "I can ride a bike.", translation: "나는 자전거를 탈 수 있어요.", mnemonic: "두 바퀴로 씽씽 달리는 **바이크**!" },
    'street': { example: "Be careful when you cross the street.", translation: "길을 건널 때는 조심해야 해요.", mnemonic: "자동차가 다니는 넓은 **스트리트**!" },
    'park': { example: "Let's play in the park.", translation: "공원에서 놀자.", mnemonic: "나무와 벤치가 있는 **파크**!" },
    'tree': { example: "The tree has green leaves.", translation: "그 나무는 초록색 잎을 가지고 있어요.", mnemonic: "시원한 그늘을 만들어주는 **트리**!" },
    'flower': { example: "The flower smells sweet.", translation: "그 꽃은 달콤한 향기가 나요.", mnemonic: "알록달록 예쁜 **플라워**!" },
    'sun': { example: "The sun is shining brightly.", translation: "해가 밝게 빛나고 있어요.", mnemonic: "낮을 밝혀주는 동그란 **썬**!" },
    'moon': { example: "The moon is beautiful tonight.", translation: "오늘 밤 달이 아름다워요.", mnemonic: "밤하늘에 뜨는 노란 **문**!" },
    'star': { example: "I see a shining star in the sky.", translation: "하늘에서 빛나는 별이 보여요.", mnemonic: "밤하늘에서 반짝반짝 빛나는 **스타**!" },
    'sky': { example: "The sky is blue.", translation: "하늘은 파랗다.", mnemonic: "구름이 둥둥 떠다니는 높은 **스카이**!" },
    'rain': { example: "I like the sound of rain.", translation: "나는 빗소리를 좋아해요.", mnemonic: "하늘에서 주룩주룩 내리는 **레인**!" },
    'snow': { example: "Let's make a snowman.", translation: "우리 눈사람 만들자.", mnemonic: "하얀 **스노우**가 펑펑 내려요." },
    'cloud': { example: "A white cloud looks like a sheep.", translation: "흰 구름이 양처럼 보여요.", mnemonic: "하늘에 솜사탕처럼 떠 있는 **클라우드**!" },
    'day': { example: "Have a nice day!", translation: "좋은 하루 보내세요!", mnemonic: "해가 떠 있는 오늘은 즐거운 **데이**!" },
    'night': { example: "I sleep at night.", translation: "나는 밤에 잠을 자요.", mnemonic: "달과 별이 뜨는 깜깜한 **나이트**!" },
    'morning': { example: "Good morning!", translation: "좋은 아침!", mnemonic: "해가 떠오르는 상쾌한 **모닝**!" },
    'evening': { example: "I watch TV in the evening.", translation: "나는 저녁에 TV를 봐요.", mnemonic: "해가 지는 노을빛 **이브닝**!" },
    'happy': { example: "I feel happy when I play with my friends.", translation: "나는 친구들과 놀 때 행복해요.", mnemonic: "웃음이 나는 **해피**한 기분!" },
    'sad': { example: "The movie was very sad.", translation: "그 영화는 매우 슬펐어요.", mnemonic: "눈물이 나는 **새드**한 이야기." },
    'big': { example: "An elephant is a big animal.", translation: "코끼리는 큰 동물이에요.", mnemonic: "아주아주 커다란 **빅** 사이즈!" },
    'small': { example: "An ant is a small insect.", translation: "개미는 작은 곤충이에요.", mnemonic: "아주아주 조그만 **스몰** 사이즈!" },
    'long': { example: "A giraffe has a long neck.", translation: "기린은 목이 길어요.", mnemonic: "기차처럼 **롱**~한 길이!" },
    'short': { example: "My pencil is short.", translation: "내 연필은 짧아요.", mnemonic: "키가 작은 **쇼트**다리!" },
    'hot': { example: "The soup is hot.", translation: "수프가 뜨거워요.", mnemonic: "\"앗, 뜨거!\" 여름은 너무 **핫**해!" },
    'cold': { example: "The ice cream is cold.", translation: "아이스크림은 차가워요.", mnemonic: "\"으, 추워!\" 겨울은 너무 **콜드**해!" },
    'good': { example: "You did a good job.", translation: "아주 잘했어요.", mnemonic: "\"참 잘했어요!\" **굿**!" },
    'bad': { example: "That is a bad idea.", translation: "그건 나쁜 생각이야.", mnemonic: "\"그러면 안 돼!\" **배드**!" },
    'up': { example: "Look up at the sky.", translation: "하늘을 올려다보세요.", mnemonic: "풍선이 하늘 위로 **업**!" },
    'down': { example: "Please sit down.", translation: "앉아주세요.", mnemonic: "계단 아래로 **다운**!" },
    'left': { example: "Turn left at the corner.", translation: "모퉁이에서 왼쪽으로 도세요.", mnemonic: "밥 먹는 손 말고 다른 쪽, **레프트**!" },
    'right': { example: "Raise your right hand.", translation: "오른손을 드세요.", mnemonic: "글씨 쓰는 손, **라이트**! (오른손잡이 기준)" },
    'run': { example: "I can run fast.", translation: "나는 빨리 달릴 수 있어요.", mnemonic: "운동장에서 쌩쌩 **런**!" },
    'walk': { example: "I walk to school with my friend.", translation: "나는 친구와 함께 걸어서 학교에 가요.", mnemonic: "공원을 천천히 **워크**!" },
    'jump': { example: "Let's jump high.", translation: "높이 점프하자.", mnemonic: "개구리처럼 폴짝 **점프**!" },
    'sit': { example: "Please sit here.", translation: "여기 앉으세요.", mnemonic: "의자에 엉덩이를 대고 **싯**!" },
    'stand': { example: "Stand up, please.", translation: "일어서 주세요.", mnemonic: "두 발로 꼿꼿하게 **스탠드**!" },
    'eat': { example: "What do you want to eat?", translation: "무엇을 먹고 싶니?", mnemonic: "맛있는 음식을 냠냠 **이트**!" },
    'drink': { example: "I drink juice in the morning.", translation: "나는 아침에 주스를 마셔요.", mnemonic: "시원한 주스를 꿀꺽 **드링크**!" },
    'read': { example: "I can read English books.", translation: "나는 영어 책을 읽을 수 있어요.", mnemonic: "책을 소리 내어 **리드**!" },
    'write': { example: "I write a letter to my friend.", translation: "나는 친구에게 편지를 써요.", mnemonic: "연필로 내 이름을 **라이트**!" },
    'play': { example: "Let's play outside.", translation: "밖에서 놀자.", mnemonic: "친구들과 신나게 **플레이**!" },
    'sing': { example: "Can you sing a song?", translation: "노래 한 곡 불러줄 수 있니?", mnemonic: "\"랄랄라\" 즐겁게 **싱**!" },
    'dance': { example: "I like to dance to music.", translation: "나는 음악에 맞춰 춤추는 것을 좋아해요.", mnemonic: "신나는 음악에 맞춰 **댄스**!" },
    'open': { example: "Please open the box.", translation: "상자를 열어주세요.", mnemonic: "문을 활짝 **오픈**!" },
    'close': { example: "Close your eyes.", translation: "눈을 감으세요.", mnemonic: "창문을 꽉 **클로즈**!" },
    'come': { example: "Come here, please.", translation: "이리 오세요.", mnemonic: "\"이리 와!\" 하고 **컴**!" },
    'go': { example: "Let's go to the park.", translation: "공원에 가자.", mnemonic: "\"저기로 가자!\" **고**!" },
    'see': { example: "I can see a rainbow.", translation: "무지개가 보여요.", mnemonic: "두 눈으로 세상을 **씨**!" },
    'hear': { example: "I can hear music.", translation: "음악 소리가 들려요.", mnemonic: "두 귀로 소리를 **히어**!" },
    'talk': { example: "Let's talk about the story.", translation: "그 이야기에 대해 이야기해 보자.", mnemonic: "친구와 재잘재잘 **토크**!" },
    'listen': { example: "Listen to the teacher carefully.", translation: "선생님 말씀을 주의 깊게 들으세요.", mnemonic: "음악을 조용히 **리슨**!" },
    'give': { example: "Please give me the book.", translation: "그 책을 저에게 주세요.", mnemonic: "선물을 **기브**!" },
    'take': { example: "Take an umbrella with you.", translation: "우산을 가져가세요.", mnemonic: "내 가방을 **테이크**!" },
    'make': { example: "I can make a paper airplane.", translation: "나는 종이비행기를 만들 수 있어요.", mnemonic: "찰흙으로 무언가를 **메이크**!" },
    'find': { example: "I can't find my keys.", translation: "내 열쇠를 못 찾겠어요.", mnemonic: "숨겨진 보물을 **파인드**!" },
    'help': { example: "Can you help me?", translation: "저를 도와줄 수 있나요?", mnemonic: "\"도와주세요!\" **헬프** 미!" },
    'love': { example: "I love my mom and dad.", translation: "나는 엄마와 아빠를 사랑해요.", mnemonic: "하트 뿅뿅 **러브**!" },
    'like': { example: "I like strawberries.", translation: "나는 딸기를 좋아해요.", mnemonic: "\"좋아요\" 버튼을 **라이크**!" },
    'want': { example: "I want a new toy.", translation: "나는 새 장난감을 원해요.", mnemonic: "\"저거 갖고 싶어!\" **원트**!" },
    'need': { example: "I need some water.", translation: "나는 물이 좀 필요해요.", mnemonic: "꼭 있어야 해, **니드**!" },
    'wash': { example: "Wash your hands before you eat.", translation: "먹기 전에 손을 씻으세요.", mnemonic: "비누로 깨끗하게 **워시**!" },
    'clean': { example: "I clean my desk.", translation: "나는 내 책상을 청소해요.", mnemonic: "방을 반짝반짝 **클린**!" },
    'stop': { example: "Stop! The light is red.", translation: "멈춰요! 빨간불이에요.", mnemonic: "빨간 신호등 앞에서 **스톱**!" },
    'start': { example: "Let's start the game.", translation: "게임을 시작하자.", mnemonic: "\"준비, 땅!\" 하고 **스타트**!" },
    'laugh': { example: "The story makes me laugh.", translation: "그 이야기는 나를 웃게 만들어요.", mnemonic: "\"하하하\" 크게 **래프**!" },
    'cry': { example: "The baby starts to cry.", translation: "아기가 울기 시작해요.", mnemonic: "\"엉엉\" 슬퍼서 **크라이**!" },
    'sleep': { example: "I sleep for eight hours every night.", translation: "나는 매일 밤 8시간 동안 자요.", mnemonic: "침대에서 코~ **슬립**!" },
  },
  mid: {
    'ability': { example: "He has the ability to solve complex problems.", translation: "그는 복잡한 문제를 해결할 능력이 있다.", mnemonic: "'able(할 수 있는)'에서 온 단어! '할 수 있음' 그 자체가 바로 '어빌리티(ability)'!" },
    'accident': { example: "The traffic accident caused a long delay.", translation: "그 교통사고는 긴 지연을 유발했다.", mnemonic: "'액!' 소리 나는 갑작스러운 '사고(accident)'를 기억하세요." },
    'achieve': { example: "She worked hard to achieve her goals.", translation: "그녀는 목표를 성취하기 위해 열심히 일했다.", mnemonic: "'아, 치부했다!'라고 외칠 만큼 무언가를 '성취하다'." },
    'active': { example: "It's important to stay active for good health.", translation: "좋은 건강을 위해 활동적인 상태를 유지하는 것이 중요하다.", mnemonic: "'액션(action)' 영화 주인공처럼 '활동적인(active)' 모습!" },
    'advice': { example: "Can you give me some advice on this matter?", translation: "이 문제에 대해 조언 좀 해줄 수 있나요?", mnemonic: "'어두운 바이스(vice-악)'를 피하라고 해주는 '조언(advice)'." },
    'afford': { example: "I can't afford to buy a new car right now.", translation: "나는 지금 당장 새 차를 살 여유가 없다.", mnemonic: "'어, 포드(Ford) 자동차' 살 '여유가 있다'니 부럽다!" },
    'agree': { example: "We all agree on the plan.", translation: "우리는 모두 그 계획에 동의한다.", mnemonic: "'어, 그리(agree) 생각한다면 나도 동의해!'" },
    'allow': { example: "My parents don't allow me to stay out late.", translation: "부모님은 내가 늦게까지 밖에 있는 것을 허락하지 않으신다.", mnemonic: "'올라와(allow)'도 좋다고 '허락하다'." },
    'almost': { example: "I'm almost finished with my homework.", translation: "나는 숙제를 거의 다 끝냈다.", mnemonic: "'올(all) 모스트(most)', 모든 것의 대부분이니 '거의' 다 한 것!" },
    'alone': { example: "He likes to spend time alone.", translation: "그는 혼자 시간을 보내는 것을 좋아한다.", mnemonic: "'얼른(alone)' 혼자 있고 싶어!" },
    'along': { example: "We walked along the river.", translation: "우리는 강을 따라 걸었다.", mnemonic: "'아, 롱(long) 길다!' 이 긴 길을 '따라' 가자." },
    'already': { example: "I have already eaten lunch.", translation: "나는 이미 점심을 먹었다.", mnemonic: "'올(all) 레디(ready)'! 모든 준비가 '이미' 끝났다!" },
    'although': { example: "Although it was cold, he went out without a coat.", translation: "비록 추웠지만, 그는 코트 없이 외출했다.", mnemonic: "'올(all) 도우(though)'! 모든 걸 다 안다 '할지라도' 겸손해야 해." },
    'amount': { example: "A large amount of money was stolen.", translation: "많은 양의 돈이 도난당했다.", mnemonic: "'아, 마운트(mount-산)'! 산더미 같은 '양'." },
    'ancient': { example: "We visited the ancient ruins in Rome.", translation: "우리는 로마의 고대 유적지를 방문했다.", mnemonic: "'에인션트(ancient)'! '에이, 이전 것'이니 '고대의' 것." },
    'announce': { example: "The principal will announce the winner.", translation: "교장 선생님께서 우승자를 발표할 것이다.", mnemonic: "아나운서가 뉴스를 '발표하다(announce)'." },
    'appear': { example: "A rabbit suddenly appeared from the hat.", translation: "토끼가 갑자기 모자에서 나타났다.", mnemonic: "'어, 피어(appear)난다!' 꽃이 피어나듯 '나타나다'." },
    'apply': { example: "You should apply for the job.", translation: "그 일자리에 지원해야 한다.", mnemonic: "'애플(Apple) 라이(like)'! 애플을 좋아해서 입사 '신청하다'." },
    'area': { example: "This area is famous for its beautiful scenery.", translation: "이 지역은 아름다운 풍경으로 유명하다.", mnemonic: "'에어리어(area)'! 공기(air)가 다른 '지역'." },
    'argue': { example: "They always argue about money.", translation: "그들은 항상 돈 문제로 논쟁한다.", mnemonic: "'아, 귀(argue)' 아파! 그만 '논쟁해'." },
    'arrange': { example: "Please arrange the books on the shelf.", translation: "책들을 책장에 정리해 주세요.", mnemonic: "'어, 레인지(range)!' 정해진 범위에 맞게 '정리하다'." },
    'arrive': { example: "What time does the train arrive?", translation: "기차는 몇 시에 도착하나요?", mnemonic: "'라이벌(rival)'보다 먼저 '도착하다(arrive)'." },
    'article': { example: "I read an interesting article in the newspaper.", translation: "나는 신문에서 흥미로운 기사를 읽었다.", mnemonic: "'아, 티끌(article)' 모아 태산! 신문 '기사' 하나하나가 소중해." },
    'attend': { example: "Are you going to attend the meeting?", translation: "회의에 참석할 건가요?", mnemonic: "'어, 텐트(attend)' 치는 캠프에 '참석하다'." },
    'avoid': { example: "You should avoid eating too much junk food.", translation: "정크푸드를 너무 많이 먹는 것은 피해야 한다.", mnemonic: "'어, 보이드(void-텅 빈)'! 텅 빈 곳으로 '피하다'." },
    'balance': { example: "It's hard to keep your balance on the ice.", translation: "얼음 위에서 균형을 잡는 것은 어렵다.", mnemonic: "'밸런스(balance)' 게임처럼 양쪽의 '균형'을 맞추는 것." },
    'behavior': { example: "His behavior was very strange.", translation: "그의 행동은 매우 이상했다.", mnemonic: "'비헤이비어(behavior)'! '비(be) 해봐(have)'! 그런 '행동'을 해봐!" },
    'belong': { example: "This book belongs to me.", translation: "이 책은 내 것이다(나에게 속한다).", mnemonic: "'비 롱(be long)'! 오랫동안 여기에 '속해' 있었어." },
    'benefit': { example: "Exercise has many benefits for your health.", translation: "운동은 건강에 많은 이익을 준다.", mnemonic: "'베네핏(benefit)'! '빼내 핏(fit)'! 살을 빼내서 몸에 딱 맞는 핏을 얻는 '이익'." },
    'beyond': { example: "The mountains are beyond the river.", translation: "산들은 강 너머에 있다.", mnemonic: "'비욘드(beyond)'! '비 온 뒤' 무지개는 저 언덕을 '넘어서' 뜬다." },
    'birth': { example: "We celebrated the birth of their baby.", translation: "우리는 그들의 아기 탄생을 축하했다.", mnemonic: "'벌스(birth)'데이! '탄생'일!" },
    'blame': { example: "Don't blame me for your mistake.", translation: "너의 실수를 나에게 비난하지 마.", mnemonic: "'불내임(blame)'! 불을 낸 사람이라고 '비난하다'." },
    'block': { example: "A fallen tree is blocking the road.", translation: "쓰러진 나무가 길을 막고 있다.", mnemonic: "레고 '블록(block)'으로 길을 '막다'." },
    'blood': { example: "He lost a lot of blood in the accident.", translation: "그는 사고로 많은 피를 흘렸다.", mnemonic: "'불러도(blood)' 대답 없는 너... 피를 흘리며... (드라마 장면 연상)" },
    'board': { example: "Please write the answer on the board.", translation: "칠판에 답을 써주세요.", mnemonic: "비행기에 '탑승하려면(board)' 보딩(boarding) 패스가 필요해." },
    'borrow': { example: "Can I borrow your pencil?", translation: "연필 좀 빌릴 수 있을까요?", mnemonic: "'바로(borrow)' 쓰고 돌려줄게, '빌려줘'." },
    'brave': { example: "The firefighter was very brave.", translation: "그 소방관은 매우 용감했다.", mnemonic: "'브레이브(brave)'! '부러워'할 만큼 '용감한' 모습." },
    'breathe': { example: "It's hard to breathe in the smoky room.", translation: "연기 나는 방에서는 숨쉬기가 어렵다.", mnemonic: "'브리드(breathe)'! '불어'내고 마시며 '숨쉬다'." },
    'bridge': { example: "We crossed the bridge over the river.", translation: "우리는 강 위의 다리를 건넜다.", mnemonic: "'브리지(bridge)'! '부리지' 마, 이 다리 건널 땐." },
    'bright': { example: "The future looks bright.", translation: "미래는 밝아 보인다.", mnemonic: "'브라이트(bright)'! '보라, 빛'이 나는 '밝은' 전구." },
    'bring': { example: "Please bring me a glass of water.", translation: "물 한 잔 가져다주세요.", mnemonic: "'부릉부릉(bring)' 차에 실어 '가져오다'." },
    'build': { example: "They are going to build a new house.", translation: "그들은 새 집을 지을 것이다.", mnemonic: "'빌딩(building)'을 '짓다(build)'." },
    'burn': { example: "Be careful not to burn the toast.", translation: "토스트를 태우지 않도록 조심하세요.", mnemonic: "'번(burn)'개 맞아서 나무가 다 '타버렸네'." },
    'business': { example: "He runs a small business.", translation: "그는 작은 사업체를 운영한다.", mnemonic: "'비지니스(business)'! 바쁘게(busy) 하는 일이 '사업'." },
    'busy': { example: "I'm too busy to talk right now.", translation: "나는 지금 너무 바빠서 이야기할 수 없다.", mnemonic: "'비지(busy)'땀 흘리며 일하는 '바쁜' 하루." },
    'captain': { example: "He is the captain of the soccer team.", translation: "그는 축구팀의 주장이다.", mnemonic: "'캡틴(captain)' 아메리카! 팀의 '주장'." },
    'carry': { example: "Can you help me carry this box?", translation: "이 상자 나르는 것 좀 도와줄래요?", mnemonic: "'캐리어(carrier)'에 짐을 넣고 '나르다'." },
    'cause': { example: "What was the cause of the fire?", translation: "화재의 원인이 무엇이었나요?", mnemonic: "'코(코)에 즈(cause)'! 코에 문제가 생겨 재채기를 '일으키다'." },
    'century': { example: "The 21st century started in 2001.", translation: "21세기는 2001년에 시작되었다.", mnemonic: "100년을 의미하는 '센추리(century)'." },
    'certain': { example: "I'm certain that he is telling the truth.", translation: "나는 그가 진실을 말하고 있다고 확신한다.", mnemonic: "'썰툰(certain)'? 그 썰은 '확실한' 거야?" },
    'chance': { example: "This is your last chance.", translation: "이것이 너의 마지막 기회야.", mnemonic: "'찬스(chance)'는 '기회'!" },
    'change': { example: "People change over time.", translation: "사람들은 시간이 지나면서 변한다.", mnemonic: "'체인지(change)'! 옷을 갈아입고 '바꾸다'." },
    'character': { example: "He has a very friendly character.", translation: "그는 매우 친근한 성격을 가지고 있다.", mnemonic: "게임 '캐릭터(character)'는 저마다의 '성격'과 '등장인물' 설정이 있다." },
    'check': { example: "Please check your answers.", translation: "답을 확인하세요.", mnemonic: "'체크(check)'! 출석을 '확인하다'." },
    'choose': { example: "You have to choose between these two options.", translation: "당신은 이 두 가지 선택지 중에서 선택해야 한다.", mnemonic: "'추즈(choose)'! '추'리닝을 살까 청바지를 살까 '선택하다'." },
    'clear': { example: "The water in the lake is very clear.", translation: "호수의 물은 매우 맑다.", mnemonic: "'클리어(clear)'! 게임을 깨끗하게 '클리어'했다!" },
    'climb': { example: "We climbed the mountain yesterday.", translation: "우리는 어제 산을 올랐다.", mnemonic: "'클라임(climb)'! '큰 라임'을 따러 나무를 '오르다'." },
    'close': { example: "Please close the window. / My house is close to the school.", translation: "창문을 닫아주세요. / 우리 집은 학교에서 가깝다.", mnemonic: "'클로즈(close)'업! '가까이'에서 찍고 가게 문을 '닫다'." },
    'cloud': { example: "The sun is behind a big cloud.", translation: "해가 큰 구름 뒤에 있다.", mnemonic: "'클라우드(cloud)'! 하늘에 둥실 떠 있는 '구름'." },
    'collect': { example: "I like to collect stamps.", translation: "나는 우표 모으는 것을 좋아한다.", mnemonic: "'콜렉트(collect)' 콜! 전화해서 친구들을 '모으다'." },
    'common': { example: "It's a common mistake.", translation: "그건 흔한 실수야.", mnemonic: "'커먼(common)'! 이리 와봐, 이건 '흔한' 일이야." },
    'compare': { example: "Don't compare yourself to others.", translation: "자신을 다른 사람과 비교하지 마세요.", mnemonic: "'컴(come), 페어(pair)'! 이리 와서 한 '쌍'을 '비교해' 보자." },
    'complete': { example: "I need to complete this report by Friday.", translation: "나는 이 보고서를 금요일까지 완성해야 한다.", mnemonic: "'컴플리트(complete)'! 퍼즐을 '완성하다'." },
    'condition': { example: "The car is in good condition.", translation: "그 차는 상태가 좋다.", mnemonic: "'컨디션(condition)'이 좋다 = '상태'가 좋다." },
    'connect': { example: "The bridge connects the two islands.", translation: "그 다리는 두 섬을 연결한다.", mnemonic: "'커넥트(connect)'! 콘센트에 플러그를 '연결하다'." },
    'contain': { example: "This box contains old photographs.", translation: "이 상자에는 오래된 사진들이 들어 있다.", mnemonic: "'컨테이너(container)' 박스는 물건을 '포함한다(contain)'." },
    'continue': { example: "Please continue with your story.", translation: "이야기를 계속해 주세요.", mnemonic: "'컨티뉴(continue)'? 게임에서 죽고 '계속하다'." },
    'control': { example: "You need to control your anger.", translation: "너는 너의 분노를 통제할 필요가 있다.", mnemonic: "리모트 '컨트롤(control)'러로 TV를 '통제하다'." },
    'copy': { example: "Please make a copy of this document.", translation: "이 문서를 복사해 주세요.", mnemonic: "'카피(copy)'! 그대로 '복사하다'." },
    'corner': { example: "The shop is on the corner of the street.", translation: "그 가게는 길모퉁이에 있다.", mnemonic: "'코너(corner)'킥! 경기장 '모퉁이'에서 차는 킥." },
    'correct': { example: "Is this the correct answer?", translation: "이것이 정답인가요?", mnemonic: "'코렉트(correct)'! '코를 렉' 걸리게 파는 건 '올바르지' 않아! (재미로)" },
    'cost': { example: "How much does it cost?", translation: "비용이 얼마나 드나요?", mnemonic: "'코스트(cost)'! '코' 수술하는 '비용'." },
    'count': { example: "Can you count from one to ten?", translation: "1부터 10까지 셀 수 있니?", mnemonic: "'카운트(count)'다운! 숫자를 '세다'." },
    'country': { example: "I want to travel to many different countries.", translation: "나는 많은 다른 나라들을 여행하고 싶다.", mnemonic: "'컨트리(country)' 음악은 '시골'에서 유래했어." },
    'cover': { example: "Cover the food to keep it fresh.", translation: "음식을 신선하게 유지하기 위해 덮어두세요.", mnemonic: "책 '커버(cover)'는 책을 '덮는' 것." },
    'create': { example: "God created the world in six days.", translation: "신은 6일 만에 세상을 창조했다.", mnemonic: "'크리에이터(creator)'는 콘텐츠를 '창조하는(create)' 사람." },
    'culture': { example: "I'm interested in Korean culture.", translation: "나는 한국 문화에 관심이 있다.", mnemonic: "'컬처(culture)' 쇼크! 다른 '문화'를 만나 충격을 받다." },
    'customer': { example: "The customer is always right.", translation: "손님은 언제나 옳다.", mnemonic: "'커스텀(custom)'을 요구하는 '고객(customer)'." },
    'daily': { example: "I read the daily newspaper.", translation: "나는 매일 신문을 읽는다.", mnemonic: "'데일리(daily)' 룩! '매일의' 옷차림." },
    'damage': { example: "The storm caused a lot of damage.", translation: "폭풍은 많은 피해를 입혔다.", mnemonic: "'대미지(damage)'를 입었다! 게임에서 '손해'를 보다." },
    'dangerous': { example: "It's dangerous to swim in that river.", translation: "저 강에서 수영하는 것은 위험하다.", mnemonic: "'데인저러스(dangerous)'! '데인' 적 있어, '위험해'!" },
    'decide': { example: "I can't decide what to wear.", translation: "무엇을 입을지 결정할 수 없다.", mnemonic: "'디사이드(decide)'! '뒤 사이드'로 갈지 앞 사이드로 갈지 '결정해'." },
    'decrease': { example: "The number of students has decreased.", translation: "학생 수가 줄었다.", mnemonic: "'디(de-아래로) 크리즈(crease-증가)'! 증가의 반대니까 '줄이다'." },
    'deep': { example: "The ocean is very deep.", translation: "바다는 매우 깊다.", mnemonic: "'딥(deep)' 슬립! '깊은' 잠." },
    'deliver': { example: "The mail is delivered every morning.", translation: "우편은 매일 아침 배달된다.", mnemonic: "'딜리버리(delivery)' 서비스! 음식을 '배달하다'." },
    'depend': { example: "Children depend on their parents.", translation: "아이들은 부모에게 의존한다.", mnemonic: "'디펜드(depend)'! '뒤 팬다'고 협박하며 나에게 '의존하게' 만들다니! (재미로)" },
    'describe': { example: "Can you describe the man you saw?", translation: "당신이 본 남자를 묘사해 줄 수 있나요?", mnemonic: "'디스크(disk)에 라이브(scribe-쓰다)'! 본 것을 디스크에 쓰듯이 '묘사하다'." },
    'design': { example: "She designed a beautiful dress.", translation: "그녀는 아름다운 드레스를 디자인했다.", mnemonic: "옷 '디자인(design)'은 옷을 '설계하는' 것." },
    'develop': { example: "The city has developed rapidly.", translation: "그 도시는 빠르게 발전했다.", mnemonic: "'디벨롭(develop)'! '뒤'에 있는 '벨'을 '엎'어서 더 좋은 걸로 '발전시키다'." },
    'difference': { example: "What's the difference between these two words?", translation: "이 두 단어의 차이점이 무엇인가요?", mnemonic: "'different(다른)'의 명사형! '다름'이 바로 '차이(difference)'." },
    'difficult': { example: "This math problem is very difficult.", translation: "이 수학 문제는 매우 어렵다.", mnemonic: "'디피컬트(difficult)'! '뒤'에 있는 '피'를 '컬'러로 칠하는 건 '어려워'." },
    'direction': { example: "Which direction is the station?", translation: "역은 어느 방향인가요?", mnemonic: "영화 '디렉터(director)'는 연기의 '방향'을 지시하는 사람." },
    'disappear': { example: "The magician made the rabbit disappear.", translation: "마술사는 토끼를 사라지게 했다.", mnemonic: "'dis(반대) + appear(나타나다)'! 나타나는 것의 반대니까 '사라지다'." },
    'discover': { example: "Columbus discovered America.", translation: "콜럼버스는 아메리카를 발견했다.", mnemonic: "'dis(반대) + cover(덮다)'! 덮여있던 것을 열어서 '발견하다'." },
    'distance': { example: "What's the distance from here to the airport?", translation: "여기서 공항까지의 거리가 얼마나 되나요?", mnemonic: "'디스턴스(distance)'! '디스'하는 사이에는 '거리'가 필요해." },
    'divide': { example: "Let's divide the pizza into four pieces.", translation: "피자를 네 조각으로 나누자.", mnemonic: "'디바이드(divide)'! '뒤'에 있는 '바'위들을 둘로 '나누다'." },
    'doctor': { example: "You should see a doctor.", translation: "너는 의사의 진찰을 받아야 한다.", mnemonic: "아플 때 찾아가는 '닥터(doctor)'." },
    'double': { example: "I'll have a double espresso, please.", translation: "더블 에스프레소로 주세요.", mnemonic: "'더블(double)'! '두 배'로 주세요!" },
    'draw': { example: "Can you draw a picture of a house?", translation: "집 그림을 그려줄 수 있니?", mnemonic: "'드로(draw)'잉! 그림을 '그리다'." },
    'dream': { example: "I had a strange dream last night.", translation: "나는 어젯밤에 이상한 꿈을 꿨다.", mnemonic: "\"I have a '드림(dream)'!\" 나의 '꿈'." },
  },
  high: {
    'abandon': { example: "They had to abandon the sinking ship.", translation: "그들은 가라앉는 배를 버려야만 했다.", mnemonic: "'어, 밴드(a band)'가 인기가 없어서 활동을 '포기하고' 해체했다." },
    'abstract': { example: "The painting was abstract, with many strange shapes.", translation: "그 그림은 많은 이상한 모양들을 가진 추상적인 작품이었다.", mnemonic: "'abs(없는) + tract(끌다)' -> 실체 없이 생각만으로 끌어낸 것이니 '추상적인'." },
    'abuse': { example: "He began to abuse alcohol after losing his job.", translation: "그는 직장을 잃은 후 술을 남용하기 시작했다.", mnemonic: "'ab(잘못된) + use(사용)' -> 잘못 사용하니 '남용'이고, 심하면 '학대'가 된다." },
    'accompany': { example: "Children must be accompanied by an adult.", translation: "어린이들은 반드시 성인과 동행해야 한다.", mnemonic: "'a(함께) + company(회사, 친구)' -> 친구와 함께 가니 '동행하다'." },
    'accomplish': { example: "It's amazing what you can accomplish through teamwork.", translation: "팀워크를 통해 당신이 이룰 수 있는 것은 놀랍다.", mnemonic: "'어, 컴(come) 플리즈(please)'! 이리 와서 내가 '이룬' 것 좀 봐!" },
    'accumulate': { example: "Dust and dirt soon accumulate if you don't clean.", translation: "청소하지 않으면 먼지와 흙이 곧 쌓인다.", mnemonic: "'어, 큐(cue) 물 레이트(late)'! 당구 큐를 늦게 샀더니 먼지만 '축적되다'." },
    'accurate': { example: "The report was accurate and well-written.", translation: "그 보고서는 정확하고 잘 작성되었다.", mnemonic: "'ac(향하여) + cure(치료)' -> 병을 향해 정확히 치료하니 '정확한'." },
    'adapt': { example: "Animals have to adapt to their environment to survive.", translation: "동물들은 생존하기 위해 환경에 적응해야 한다.", mnemonic: "'어댑터(adapter)'는 다른 환경에 '적응하게' 해주는 장치." },
    'adequate': { example: "The food was adequate for the number of guests.", translation: "음식은 손님 수에 비해 충분했다.", mnemonic: "'애들 컷(adequate)'! 애들이 이만큼 컸으니 용돈도 '충분하게' 줘야지." },
    'adjust': { example: "You need to adjust the mirror before you start driving.", translation: "운전을 시작하기 전에 거울을 조정해야 한다.", mnemonic: "'ad(향하여) + just(딱 맞는)' -> 딱 맞게 만드니 '조정하다'." },
    'advocate': { example: "She is a strong advocate for women's rights.", translation: "그녀는 여성 인권의 강력한 옹호자이다.", mnemonic: "'ad(향하여) + vocate(목소리)' -> ~를 향해 목소리를 내니 '옹호하다'." },
    'alter': { example: "We had to alter our plans because of the rain.", translation: "우리는 비 때문에 계획을 변경해야 했다.", mnemonic: "'올터(alter)'! 옷 수선(alternative)해서 디자인을 '변경하다'." },
    'ambiguous': { example: "His reply was very ambiguous.", translation: "그의 대답은 매우 애매했다.", mnemonic: "'ambi(둘 다) + guous' -> 양쪽으로 다 해석되니 '애매한'." },
    'analyze': { example: "The scientists will analyze the data.", translation: "과학자들은 그 데이터를 분석할 것이다.", mnemonic: "'애널라이즈(analyze)'! '애'를 '날라'서 성분을 '분석하다'. (재미로)" },
    'anticipate': { example: "We anticipate that the project will be successful.", translation: "우리는 그 프로젝트가 성공할 것이라고 예상한다.", mnemonic: "'anti(미리) + cipate(잡다)' -> 미리 상황을 잡으니 '예상하다'." },
    'apparent': { example: "It was apparent that she was unhappy.", translation: "그녀가 불행하다는 것은 분명했다.", mnemonic: "'appear(나타나다)'에서 온 말. 눈앞에 나타난 것처럼 '분명한'." },
    'appropriate': { example: "Please wear clothing appropriate for the occasion.", translation: "그 상황에 적절한 옷을 입어주세요.", mnemonic: "'어, 프로 프리 에이트(appropriate)'! 프로는 때와 장소에 '적절한' 행동을 해." },
    'approve': { example: "The committee approved the new budget.", translation: "위원회는 새로운 예산을 승인했다.", mnemonic: "'ap(향하여) + prove(증명)' -> 좋다고 증명되었으니 '승인하다'." },
    'artificial': { example: "This plant has artificial flowers.", translation: "이 화분에는 인공 꽃이 있다.", mnemonic: "'art(예술, 기술)'로 만든 것. 자연적이지 않은 '인공의'." },
    'assign': { example: "The teacher assigned homework to the students.", translation: "선생님은 학생들에게 숙제를 할당했다.", mnemonic: "'어, 사인(assign)'해! 이 업무는 너에게 '할당한다'는 사인." },
    'assume': { example: "I assume you know what you're doing.", translation: "나는 네가 무엇을 하는지 알고 있다고 가정한다.", mnemonic: "'어, 숨(assume)' 쉬는 걸 보니 살아있다고 '가정하다'." },
    'assure': { example: "I can assure you that you will be safe.", translation: "당신이 안전할 것이라고 보장할 수 있습니다.", mnemonic: "'as(향하여) + sure(확실한)' -> 확실하게 만들어주니 '보장하다'." },
    'attach': { example: "Please attach your photo to the application form.", translation: "지원서에 사진을 붙여주세요.", mnemonic: "'어, 터치(attach)'! 풀로 '터치'해서 '붙이다'." },
    'attempt': { example: "He made an attempt to break the world record.", translation: "그는 세계 기록을 깨려는 시도를 했다.", mnemonic: "'어, 템트(tempt-유혹)'! 유혹에 넘어가 한번 '시도하다'." },
    'attain': { example: "She worked hard to attain her goal of becoming a doctor.", translation: "그녀는 의사가 되겠다는 목표를 달성하기 위해 열심히 노력했다.", mnemonic: "'어, 텐(ten)'! 10점 만점을 '달성하다'." },
    'aware': { example: "Are you aware of the risks?", translation: "위험을 알고 있나요?", mnemonic: "'어, 왜(aware)?' 하고 묻는 건 상황을 '알고 있기' 때문." },
    'barrier': { example: "Lack of confidence is a barrier to success.", translation: "자신감 부족은 성공의 장벽이다.", mnemonic: "'배리어(barrier)'! 게임에서 공격을 막는 '장벽'." },
    'benefit': { example: "There are many benefits to regular exercise.", translation: "규칙적인 운동에는 많은 이점이 있다.", mnemonic: "'bene(좋은)'가 들어간 단어! 좋은 것이니 '이익, 혜택'." },
    'burden': { example: "I don't want to be a burden to you.", translation: "나는 당신에게 부담이 되고 싶지 않아요.", mnemonic: "'버든(burden)'! '버'티기 힘든 '든'든한 '부담'." },
    'calculate': { example: "Can you calculate the total cost?", translation: "총비용을 계산해 줄 수 있나요?", mnemonic: "'캘큘레이터(calculator-계산기)'는 '계산하는(calculate)' 기계." },
    'candidate': { example: "There are three candidates for the job.", translation: "그 일자리에 세 명의 후보자가 있다.", mnemonic: "'캔디 데이트(candidate)'! 달콤한 데이트를 약속하는 선거 '후보자'." },
    'capacity': { example: "The stadium has a seating capacity of 50,000.", translation: "그 경기장은 5만 명의 좌석 수용력을 가지고 있다.", mnemonic: "'캡(cap-모자)'의 '크기(capacity)'! 모자가 얼마나 담을 수 있는지 '수용력'." },
    'capture': { example: "The police captured the thief.", translation: "경찰은 도둑을 붙잡았다.", mnemonic: "사진을 '캡처(capture)'하는 것은 순간을 '붙잡는' 것." },
    'cease': { example: "The company has decided to cease operations.", translation: "그 회사는 운영을 중단하기로 결정했다.", mnemonic: "'씨, 이즈(cease)'! 이젠 그만! 하고 '중단하다'." },
    'challenge': { example: "Climbing the mountain was a real challenge.", translation: "그 산을 오르는 것은 진정한 도전이었다.", mnemonic: "'챌린지(challenge)'! 어려운 과제에 '도전'하다." },
    'circumstance': { example: "Under no circumstances should you open that door.", translation: "어떤 상황에서도 그 문을 열어서는 안 된다.", mnemonic: "'써컴(circum-주변) 스탠스(stance-서다)' -> 주변에 서 있는 것들이 바로 '상황'." },
    'collapse': { example: "The old building collapsed in the earthquake.", translation: "그 낡은 건물은 지진으로 붕괴했다.", mnemonic: "'콜라(colla)를 랩(pse)'으로 쌌더니 압력 때문에 '붕괴하다'." },
    'colleague': { example: "I'm going out for lunch with a colleague.", translation: "나는 동료와 점심을 먹으러 나간다.", mnemonic: "'칼리지(college)'에서 만난 '동료(colleague)'." },
    'commit': { example: "He was sent to prison for a crime he didn't commit.", translation: "그는 저지르지 않은 범죄로 감옥에 보내졌다.", mnemonic: "'컴(come) 잇(it)'! 이리 와서 이 일에 '헌신해'! 또는 범죄를 '저지르다'. (문맥 중요)" },
    'compensate': { example: "We will compensate you for your loss.", translation: "우리는 당신의 손실에 대해 보상할 것입니다.", mnemonic: "'컴(come), 펜 세이트(pen sate)'! 이리 와서 펜 값이라도 '보상해' 줄게." },
    'compile': { example: "She compiled a list of all the books she had read.", translation: "그녀는 자신이 읽었던 모든 책의 목록을 편집했다.", mnemonic: "'컴(come), 파일(pile)'! 이리 와서 자료들을 쌓아 '편집하자'." },
    'complain': { example: "The customer complained about the slow service.", translation: "그 고객은 느린 서비스에 대해 불평했다.", mnemonic: "'컴(come), 플레인(plain)'! 이리 와서 '평범하게'만 해주지 말고 더 잘하라고 '불평하다'." },
    'component': { example: "The main component of the machine is a small motor.", translation: "그 기계의 주요 구성 요소는 작은 모터이다.", mnemonic: "'컴(com-함께) 포넌트(ponent-놓다)' -> 함께 놓여있는 것들이 '구성 요소'." },
    'comprise': { example: "The team is comprised of ten members.", translation: "그 팀은 10명의 멤버로 구성되어 있다.", mnemonic: "'컴(com-함께) 프라이즈(prise-잡다)' -> 함께 잡고 있으니 하나의 팀을 '구성하다'." },
    'concentrate': { example: "I can't concentrate with all that noise.", translation: "저 모든 소음 때문에 집중할 수가 없다.", mnemonic: "'콘센트(concentrate)'에 플러그 꽂듯이 정신을 한 곳에 '집중하다'." },
    'conclude': { example: "The report concludes that the new drug is effective.", translation: "그 보고서는 신약이 효과적이라고 결론짓는다.", mnemonic: "'con(함께) + clude(닫다)' -> 함께 이야기를 닫으면서 '결론짓다'." },
    'concrete': { example: "We need concrete evidence, not just rumors.", translation: "우리는 단지 소문이 아닌 구체적인 증거가 필요하다.", mnemonic: "'콘크리트(concrete)'처럼 단단하고 형태가 있으니 '구체적인'." },
    'conduct': { example: "The orchestra was conducted by a famous musician.", translation: "그 오케스트라는 유명한 음악가에 의해 지휘(수행)되었다.", mnemonic: "'콘서트(concert)'를 '덕트(duct)' 테이프로 준비하며 '수행하다'." },
    'confirm': { example: "Please confirm your reservation.", translation: "예약을 확인해 주세요.", mnemonic: "'con(완전히) + firm(단단한)' -> 완전히 단단하게 만드니 '확인하다'." },
    'conflict': { example: "The two countries have been in conflict for years.", translation: "두 나라는 수년간 갈등을 겪어왔다.", mnemonic: "'con(함께) + flict(치다)' -> 서로 함께 치고받으니 '갈등, 충돌'." },
    'conform': { example: "You must conform to the rules.", translation: "당신은 규칙에 순응해야 한다.", mnemonic: "'con(함께) + form(형태)' -> 다른 사람들과 같은 형태로 만드니 '순응하다'." },
    'consequence': { example: "Every action has a consequence.", translation: "모든 행동에는 결과가 따른다.", mnemonic: "'con(함께) + sequence(순서)' -> 행동과 함께 순서대로 따라오는 것, '결과'." },
    'considerable': { example: "The project requires a considerable amount of time.", translation: "그 프로젝트는 상당한 양의 시간을 필요로 한다.", mnemonic: "'consider(고려하다)'할 만한 가치가 있을 정도로 '상당한'." },
    'consist': { example: "The committee consists of ten members.", translation: "위원회는 10명의 위원으로 이루어져 있다.", mnemonic: "'con(함께) + sist(서다)' -> 여러 사람이 함께 서 있으니 팀이 '이루어져 있다'." },
    'constant': { example: "The machine makes a constant humming noise.", translation: "그 기계는 지속적인 윙윙거리는 소리를 낸다.", mnemonic: "'콘스탄트(constant)'! '콘'서트가 '스탠'딩으로 '지속적으로' 이어진다." },
    'construct': { example: "They plan to construct a new bridge.", translation: "그들은 새로운 다리를 건설할 계획이다.", mnemonic: "'con(함께) + struct(세우다)' -> 함께 구조물을 세우니 '건설하다'." },
    'consume': { example: "This car consumes a lot of fuel.", translation: "이 차는 많은 연료를 소비한다.", mnemonic: "'컨슈머(consumer)'는 물건을 '소비하는(consume)' 사람." },
    'contribute': { example: "Everyone should contribute to the community.", translation: "모든 사람은 지역 사회에 기여해야 한다.", mnemonic: "'컨트리(country)에 뷰트(bute)'! 나라에 아름다움을 '기여하다'." },
    'controversy': { example: "The new law caused a lot of controversy.", translation: "그 새로운 법은 많은 논란을 일으켰다.", mnemonic: "'contro(반대) + versy(돌다)' -> 서로 반대 방향으로 돌며 싸우니 '논란'." },
    'convenient': { example: "The new subway line is very convenient for me.", translation: "새로 생긴 지하철 노선은 나에게 매우 편리하다.", mnemonic: "'컨비니언스(convenience)' 스토어는 '편리한' 가게(편의점)." },
    'convert': { example: "They converted the old factory into apartments.", translation: "그들은 낡은 공장을 아파트로 전환했다.", mnemonic: "'컨버터(converter)'는 신호를 '전환하는' 장치." },
    'cooperate': { example: "Let's cooperate to finish the project on time.", translation: "프로젝트를 제시간에 끝내기 위해 협력합시다.", mnemonic: "'co(함께) + operate(작동하다)' -> 함께 작동하니 '협력하다'." },
    'cope': { example: "He is trying to cope with the stress of his new job.", translation: "그는 새 직장의 스트레스에 대처하려고 노력하고 있다.", mnemonic: "'코피(cope)'가 나도 참고 상황에 '대처하다'." },
    'corporate': { example: "He works in the corporate finance department.", translation: "그는 기업 재무 부서에서 일한다.", mnemonic: "'corporation(기업)'의 형용사형! '기업의'." },
    'correspond': { example: "Your account of the event does not correspond with hers.", translation: "그 사건에 대한 당신의 설명은 그녀의 것과 일치하지 않는다.", mnemonic: "'cor(함께) + respond(응답하다)' -> 서로 똑같이 응답하니 '일치하다'." },
    'crucial': { example: "It's crucial that we arrive on time.", translation: "우리가 제시간에 도착하는 것이 결정적으로 중요하다.", mnemonic: "'크루셜(crucial)'! '그릇이' 깨지느냐 마느냐의 '결정적인' 순간." },
    'cultivate': { example: "The farmers cultivate rice in the fields.", translation: "농부들은 들판에서 쌀을 경작한다.", mnemonic: "'컬처(culture-문화)'는 정신을 '개발하는' 것, 땅을 '경작하는' 것과 같다." },
    'dedicate': { example: "She dedicates her life to helping the poor.", translation: "그녀는 가난한 사람들을 돕는 데 평생을 헌신한다.", mnemonic: "'대디, 케이트(dedicate)'! 아빠는 케이트에게 모든 것을 '헌신한다'." },
    'defend': { example: "The soldiers defended the castle from the enemy.", translation: "군인들은 적으로부터 성을 방어했다.", mnemonic: "'디펜스(defense)'! 수비, '방어'." },
    'demonstrate': { example: "The teacher demonstrated the experiment to the class.", translation: "선생님은 학생들에게 실험을 시연했다.", mnemonic: "'데모(demo)' 버전은 제품을 '시연하는' 것." },
    'deny': { example: "He denied that he had stolen the money.", translation: "그는 돈을 훔쳤다는 것을 부인했다.", mnemonic: "'디나이(deny)'! '뒤'에서 '나이'를 속인 사실을 '부인하다'." },
    'depart': { example: "The train will depart from platform 5.", translation: "기차는 5번 플랫폼에서 떠날 것이다.", mnemonic: "'디파트(depart)'! '디'파트먼트 스토어(백화점)를 '떠나다'." },
    'depress': { example: "The rainy weather always depresses me.", translation: "비 오는 날씨는 항상 나를 우울하게 한다.", mnemonic: "'de(아래로) + press(누르다)' -> 기분을 아래로 꾹 누르니 '우울하게 하다'." },
    'derive': { example: "The word \"derive\" derives from a Latin word.", translation: "'derive'라는 단어는 라틴어 단어에서 유래했다.", mnemonic: "'드라이브(drive)'해서 강에서 물을 '끌어내다'." },
    'deserve': { example: "You deserve a reward for your hard work.", translation: "당신은 열심히 일한 것에 대해 보상을 받을 가치가 있다.", mnemonic: "'디저트(dessert)'는 열심히 일한 당신이 '받을 가치가 있는' 것." },
    'detect': { example: "The machine can detect very small amounts of radiation.", translation: "그 기계는 아주 적은 양의 방사능도 감지할 수 있다.", mnemonic: "'디텍티브(detective-탐정)'는 단서를 '감지하는' 사람." },
    'determine': { example: "Your attitude will determine your success.", translation: "당신의 태도가 당신의 성공을 결정할 것이다.", mnemonic: "'디, 터민(determine)'! '뒤'에 있는 '터'미널로 갈지 '결정하다'." },
    'diminish': { example: "The world's natural resources are diminishing.", translation: "세계의 천연자원이 줄어들고 있다.", mnemonic: "'뒤'에 '미니(mini)' 사이즈로 '줄어들다'." },
    'discipline': { example: "It takes a lot of discipline to practice every day.", translation: "매일 연습하는 데는 많은 규율이 필요하다.", mnemonic: "'디스(this) 플랜(plan)'! 이 계획을 따르는 '규율'이 필요해." },
    'distinguish': { example: "I can't distinguish between the two twins.", translation: "나는 그 두 쌍둥이를 구별할 수 없다.", mnemonic: "'디스(this) 팅(thing) 귀신'? 이것이 물건인지 귀신인지 '구별하다'." },
    'distribute': { example: "The organization distributed food to the homeless.", translation: "그 단체는 노숙자들에게 음식을 분배했다.", mnemonic: "'뒤'에서 '트리'에 '뷰티'풀한 장식을 '분배해서' 달다." },
    'domestic': { example: "The airline offers both domestic and international flights.", translation: "그 항공사는 국내선과 국제선 항공편을 모두 제공한다.", mnemonic: "'도메스틱(domestic)'! '도'둑이 '메'고 '스틱'을 든 건 '가정'불화 때문이야. (재미로)" },
    'dominate': { example: "The company dominates the market for soft drinks.", translation: "그 회사는 청량음료 시장을 지배한다.", mnemonic: "'도미네이트(dominate)'! '도미'가 '네이트' 판을 '지배하다'." },
    'eliminate': { example: "We need to eliminate the possibility of error.", translation: "우리는 오류의 가능성을 제거해야 한다.", mnemonic: "'이리(eli) 미네(minate)'! 이리 와서 먼지를 '밀어서' '제거해'." },
    'emerge': { example: "The sun emerged from behind the clouds.", translation: "해가 구름 뒤에서 나타났다.", mnemonic: "'이머전시(emergency)'! 응급상황에 구급차가 '나타나다'." },
    'emphasize': { example: "The teacher emphasized the importance of studying.", translation: "선생님은 공부의 중요성을 강조했다.", mnemonic: "'엠퍼(em-만들다) 사이즈(size)'! 사이즈를 크게 만들어서 '강조하다'." },
    'enable': { example: "This ticket will enable you to enter the museum.", translation: "이 티켓은 당신이 박물관에 들어가는 것을 가능하게 할 것이다.", mnemonic: "'en(만들다) + able(할 수 있는)' -> 할 수 있게 만드니 '가능하게 하다'." },
    'encounter': { example: "I encountered an old friend at the store.", translation: "나는 가게에서 옛 친구와 우연히 마주쳤다.", mnemonic: "'인(in) 카운터(counter)'! 카운터 안에서 적과 '마주치다'." },
    'enhance': { example: "The new software will enhance the computer's performance.", translation: "새로운 소프트웨어는 컴퓨터의 성능을 향상시킬 것이다.", mnemonic: "'인핸스(enhance)'! '인'삼을 먹고 '핸'드폰 성능을 '향상시키다'." },
    'ensure': { example: "Please ensure that all the lights are turned off.", translation: "모든 불이 꺼졌는지 반드시 보장(확인)해 주세요.", mnemonic: "'en(만들다) + sure(확실한)' -> 확실하게 만드니 '보장하다'. (assure와 유사)" },
    'equivalent': { example: "His monthly salary is equivalent to what I earn in a year.", translation: "그의 월급은 내가 1년 동안 버는 것과 동등하다.", mnemonic: "'equi(같은) + valent(가치)' -> 같은 가치를 지니니 '동등한'." },
    'establish': { example: "The company was established in 1950.", translation: "그 회사는 1950년에 설립되었다.", mnemonic: "'이, 스태프 블리 쉬(establish)'! 이 스태프들을 데리고 회사를 '설립하자'." },
    'evaluate': { example: "The teacher will evaluate your performance.", translation: "선생님께서 당신의 수행을 평가할 것입니다.", mnemonic: "'e(밖으로) + value(가치)' -> 가치를 밖으로 꺼내 보이게 하니 '평가하다'." },
    'evolve': { example: "Humans evolved from apes.", translation: "인간은 유인원으로부터 진화했다.", mnemonic: "포켓몬이 '이볼브(evolve)'해서 '진화하다'." },
    'exceed': { example: "The cost must not exceed the budget.", translation: "비용이 예산을 초과해서는 안 된다.", mnemonic: "'엑시드(exceed)'! '엑셀(excel)' 밟아서 제한 속도를 '초과하다'." },
    'exclude': { example: "The price excludes tax.", translation: "그 가격은 세금을 제외한 것이다.", mnemonic: "'ex(밖으로) + clude(닫다)' -> 문을 닫고 밖으로 내보내니 '제외하다'." },
    'expand': { example: "The company plans to expand its business in Asia.", translation: "그 회사는 아시아에서 사업을 확장할 계획이다.", mnemonic: "'익스팬드(expand)'! '익스'프레스(고속)로 영토를 '확장하다'." },
    'exploit': { example: "Some companies exploit their workers.", translation: "일부 회사들은 노동자들을 착취한다.", mnemonic: "'익스(ex) 플로잇(exploit)'! '전' 여친의 비밀을 '이용해서' 돈을 벌다니, 나쁜 '착취'야." },
    'expose': { example: "He was exposed as a spy.", translation: "그는 스파이임이 드러났다.", mnemonic: "'ex(밖으로) + pose(놓다)' -> 밖에다 놓으니 비밀이 '드러나다'." },
    'extend': { example: "Can I extend my stay for two more days?", translation: "제 체류를 이틀 더 연장할 수 있을까요?", mnemonic: "'익스텐드(extend)'! '익스'텐션(extension) 코드로 길이를 '연장하다'." },
  },
  uni: {
    'abolish': { example: "The government voted to abolish the old tax law.", translation: "정부는 낡은 세법을 폐지하기로 투표했다.", mnemonic: "'어, 볼일(abolish) 다 봤으니' 그 제도는 이제 '폐지해'!" },
    'abrupt': { example: "The meeting came to an abrupt end.", translation: "회의는 갑작스럽게 끝났다.", mnemonic: "'ab(이탈) + rupt(깨다)' -> 정상 궤도를 이탈하여 깨지니 '갑작스러운'." },
    'abundant': { example: "The country has abundant natural resources.", translation: "그 나라는 풍부한 천연자원을 가지고 있다.", mnemonic: "'어, 번 돈 투(abundant)'! 번 돈이 많아서 자원이 '풍부한'." },
    'accessible': { example: "The museum is easily accessible by public transport.", translation: "그 박물관은 대중교통으로 쉽게 접근 가능하다.", mnemonic: "'access(접근)' + 'able(가능한)' -> '접근 가능한'." },
    'accommodate': { example: "The hotel can accommodate up to 500 guests.", translation: "그 호텔은 최대 500명의 손님을 수용할 수 있다.", mnemonic: "'어, 카(car) 뭐 데이트(accommodate)'! 차까지 데이트에 제공하며 '편의를 제공하다'." },
    'accompany': { example: "He was accompanied by his lawyer.", translation: "그는 그의 변호사를 동반했다.", mnemonic: "'a(함께) + company(회사, 동료)' -> 동료와 함께 가니 '동반하다'." },
    'accomplish': { example: "We have a lot to accomplish today.", translation: "우리는 오늘 완수해야 할 일이 많다.", mnemonic: "'어, 컴(come) 플리즈(please)'! 이리 와서 내가 '완수한' 과제 좀 봐." },
    'accumulate': { example: "He accumulated a fortune through his business.", translation: "그는 사업을 통해 부를 축적했다.", mnemonic: "'ac(향하여) + cumulate(쌓다)' -> 한 곳을 향해 계속 쌓으니 '축적하다'." },
    'acquisition': { example: "Language acquisition starts at a very young age.", translation: "언어 습득은 매우 어린 나이에 시작된다.", mnemonic: "'acquire(얻다)'의 명사형. 지식이나 자산을 얻는 것, '습득, 취득'." },
    'adjacent': { example: "They live in a house adjacent to the railway.", translation: "그들은 철도에 인접한 집에 산다.", mnemonic: "'애드(ad-가까이) 제이슨(Jason)트' -> 제이슨네 집 바로 옆, '인접한' 곳." },
    'advocate': { example: "He advocates for environmental protection.", translation: "그는 환경 보호를 옹호한다.", mnemonic: "'ad(향하여) + voc(목소리)' -> ~를 향해 목소리를 내니 '옹호하다'." },
    'aggregate': { example: "The aggregate score of the two games was 5-3.", translation: "두 경기의 총합 점수는 5대 3이었다.", mnemonic: "'애, 그리 게이트(aggregate)'로 다 '모여'! '총합'을 보자." },
    'allocate': { example: "The government allocated funds for the new project.", translation: "정부는 새 프로젝트를 위해 자금을 할당했다.", mnemonic: "'all(모두) + locate(위치시키다)' -> 자원을 모두 제자리에 위치시키니 '할당하다'." },
    'alter': { example: "This event will not alter our plans.", translation: "이 사건이 우리의 계획을 변경하지는 않을 것이다.", mnemonic: "'alternative(대안)'은 계획을 '변경한' 것." },
    'ambiguous': { example: "The ending of the movie was ambiguous.", translation: "그 영화의 결말은 모호했다.", mnemonic: "'ambi(양쪽)' -> 양쪽으로 다 해석될 수 있으니 '모호한'." },
    'analogy': { example: "He drew an analogy between the brain and a computer.", translation: "그는 뇌와 컴퓨터 사이의 유사점을 들어 비유했다.", mnemonic: "'아, 날로지(analogy)'? 날로 먹으려는 너와 그의 '유사점'을 '비유'해볼까?" },
    'analyze': { example: "We need to analyze the results in detail.", translation: "우리는 그 결과를 상세히 분석할 필요가 있다.", mnemonic: "'ana(나누어) + lyze(풀다)' -> 나누어서 풀어보니 '분석하다'." },
    'anomaly': { example: "The scientist found an anomaly in the data.", translation: "그 과학자는 데이터에서 변칙적인 것을 발견했다.", mnemonic: "'a(not) + nomaly(normal)' -> 정상이 아니니 '변칙, 예외'." },
    'apparent': { example: "His disappointment was apparent to everyone.", translation: "그의 실망감은 모든 사람에게 명백했다.", mnemonic: "'appear(나타나다)' -> 눈앞에 나타난 것처럼 '명백한'." },
    'applicable': { example: "This rule is not applicable to new members.", translation: "이 규칙은 신입 회원에게는 적용 가능하지 않다.", mnemonic: "'apply(적용하다)' + 'able(가능한)' -> '적용 가능한'." },
    'appreciate': { example: "I really appreciate your help.", translation: "당신의 도움에 정말 감사합니다.", mnemonic: "'ap(향하여) + preciate(가치)' -> 가치를 인정하니 '감사하고, 감상하다'." },
    'arbitrary': { example: "The choice of winner seemed completely arbitrary.", translation: "우승자 선정은 완전히 임의적인 것처럼 보였다.", mnemonic: "'아, 비틀어리(arbitrary)'! 규칙을 비틀어서 '임의로' 정하다니, '독단적'이야." },
    'aspect': { example: "We must consider every aspect of the problem.", translation: "우리는 문제의 모든 측면을 고려해야 한다.", mnemonic: "'a(하나의) + spect(보다)' -> 한 방향에서 보는 '측면'." },
    'assemble': { example: "The students assembled in the main hall.", translation: "학생들은 중앙 홀에 모였다.", mnemonic: "'어셈블(assemble)'! 어벤져스 멤버들을 '모으다'." },
    'assess': { example: "The test is designed to assess your reading skills.", translation: "그 시험은 당신의 독해 능력을 평가하기 위해 고안되었다.", mnemonic: "'어, 세금(assess)'을 매기기 위해 재산을 '평가하다'." },
    'assign': { example: "The teacher assigned a new project to the class.", translation: "선생님은 반에 새로운 프로젝트를 부과했다.", mnemonic: "'어, 사인(assign)'해! 이 임무를 너에게 '할당한다'는 사인." },
    'assume': { example: "Let's assume that the story is true.", translation: "그 이야기가 사실이라고 가정해 봅시다.", mnemonic: "'어, 숨(assume)' 쉬는 걸 보니 살아있다고 '가정하다'." },
    'attain': { example: "He attained the rank of professor.", translation: "그는 교수라는 지위를 달성했다.", mnemonic: "'어, 텐(ten)'! 10점 만점을 '달성하다'." },
    'attribute': { example: "He attributed his success to hard work.", translation: "그는 자신의 성공을 노력의 결과로 보았다.", mnemonic: "'어, 트리뷰트(tribute-헌사)'! 성공은 노력에 바치는 헌사, 즉 노력의 '결과로 보다'." },
    'authorize': { example: "Only managers can authorize these payments.", translation: "관리자만이 이 지불을 승인할 수 있다.", mnemonic: "'author(저자, 권위자)'가 허락하니 '승인하다'." },
    'autonomous': { example: "The university is an autonomous institution.", translation: "그 대학은 자율적인 기관이다.", mnemonic: "'auto(스스로) + nomous(법)' -> 스스로의 법으로 움직이니 '자율적인'." },
    'behalf': { example: "I am writing on behalf of my client.", translation: "저는 제 고객을 대신하여(고객의 이익을 위해) 글을 쓰고 있습니다.", mnemonic: "'비 해프(be half)'! 그의 '절반이 되어' 그의 '편'에 서다." },
    'beneficial': { example: "A good diet is beneficial to your health.", translation: "좋은 식단은 건강에 유익하다.", mnemonic: "'bene(좋은)'가 들어간 단어! 좋은 것이니 '유익한'." },
    'bias': { example: "The news report showed a clear bias towards the government.", translation: "그 뉴스 보도는 정부에 대한 명백한 편견을 보여주었다.", mnemonic: "'바이어스(bias)'! 내 최애 아이돌에게만 향하는 '편견' 어린 사랑." },
    'bulk': { example: "The bulk of the work has already been done.", translation: "그 일의 대부분은 이미 끝났다.", mnemonic: "'벌크(bulk)'업! 몸의 '규모'를 키우는 것." },
    'capacity': { example: "The hall has a capacity of 200 people.", translation: "그 홀은 200명의 수용 용량을 가지고 있다.", mnemonic: "'cap(잡다) + acity' -> 잡을 수 있는 양, 즉 '용량, 능력'." },
    'cease': { example: "They voted to cease all military operations.", translation: "그들은 모든 군사 작전을 중단하기로 투표했다.", mnemonic: "'씨, 이젠(cease)' 그만! 하고 '중단하다'." },
    'coherent': { example: "He proposed a coherent plan for the city's development.", translation: "그는 도시 발전을 위한 일관된 계획을 제안했다.", mnemonic: "'co(함께) + here(붙다)' -> 논리가 함께 착착 붙어 있으니 '일관된'." },
    'coincide': { example: "My birthday coincides with a national holiday.", translation: "내 생일은 국경일과 동시에 일어난다(겹친다).", mnemonic: "'co(함께) + inside(안에)' -> 같은 시간 안에 함께 일어나니 '동시에 일어나다'." },
    'collapse': { example: "The roof collapsed under the weight of the snow.", translation: "지붕이 눈의 무게를 견디지 못하고 붕괴했다.", mnemonic: "'콜라(colla)를 랩(pse)'으로 쌌더니 압력에 '붕괴하다'." },
    'colleague': { example: "She discussed the project with her colleagues.", translation: "그녀는 동료들과 그 프로젝트에 대해 논의했다.", mnemonic: "'칼리지(college)'에서 만난 '동료'." },
    'commence': { example: "The ceremony will commence at noon.", translation: "행사는 정오에 시작될 것입니다.", mnemonic: "'커, 맨스(commence)'! 자, 남자들이여, 이제 '시작하자'!" },
    'commodity': { example: "Oil is a valuable commodity.", translation: "석유는 가치 있는 상품이다.", mnemonic: "'컴(come), 어디(odity)'? 이리 와봐, 어디서 이런 좋은 '상품'을 파는지." },
    'compatible': { example: "This software is not compatible with your computer.", translation: "이 소프트웨어는 당신의 컴퓨터와 양립 가능하지 않다(호환되지 않는다).", mnemonic: "'컴(com-함께) + patible(견딜 수 있는)' -> 함께 있을 수 있으니 '양립 가능한'." },
    'compile': { example: "He compiled a book of his favorite poems.", translation: "그는 자신이 가장 좋아하는 시들을 모아 책을 편집했다.", mnemonic: "'컴(come), 파일(pile)'! 이리 와서 자료들을 쌓아 '편집하자'." },
    'complement': { example: "The wine complements the food perfectly.", translation: "그 와인은 음식을 완벽하게 보완한다.", mnemonic: "'complete(완성하다)'와 비슷! 부족한 부분을 채워 완성하게 '보완하다'. (주의: compliment는 칭찬)" },
    'comprehensive': { example: "The book provides a comprehensive guide to the subject.", translation: "그 책은 그 주제에 대한 종합적인 안내서를 제공한다.", mnemonic: "'com(함께) + prehend(잡다)' -> 모든 것을 함께 잡고 있으니 '종합적인'." },
    'comprise': { example: "The United Kingdom is comprised of four countries.", translation: "영국은 4개의 나라로 구성되어 있다.", mnemonic: "'com(함께) + prise(잡다)' -> 함께 잡고 있으니 하나의 전체를 '구성하다'." },
    'compulsory': { example: "In this country, education is compulsory until the age of 16.", translation: "이 나라에서는 16세까지 교육이 의무적이다.", mnemonic: "'컴, 펄서리(compulsory)'! 이리 와서 벌 서! 이건 '의무적'이야." },
    'conceive': { example: "I cannot conceive of a world without music.", translation: "나는 음악 없는 세상을 상상할 수 없다.", mnemonic: "'콘셉트(concept)'를 머릿속으로 '생각하다(conceive)'." },
    'concurrent': { example: "He is serving two concurrent prison sentences.", translation: "그는 두 개의 징역형을 동시에 복역 중이다.", mnemonic: "'con(함께) + current(흐름)' -> 같은 시간의 흐름 속에서 일어나니 '동시에 발생하는'." },
    'confer': { example: "He conferred with his lawyers before making a decision.", translation: "그는 결정을 내리기 전에 변호사들과 상의했다.", mnemonic: "'컨퍼런스(conference)'는 함께 모여 '상의하는' 자리." },
    'confine': { example: "The animals were confined in a small cage.", translation: "동물들은 작은 우리 안에 갇혀(제한되어) 있었다.", mnemonic: "'con(함께) + fine(끝)' -> 경계를 함께 그어 끝을 정하니 '제한하다'." },
    'confirm': { example: "Please confirm your flight details.", translation: "당신의 항공편 세부 정보를 확인해 주세요.", mnemonic: "'con(완전히) + firm(단단한)' -> 완전히 단단하게 만드니 '확인하다'." },
    'conform': { example: "All students must conform to the school's dress code.", translation: "모든 학생은 학교의 복장 규정을 따라야 한다.", mnemonic: "'con(함께) + form(형태)' -> 다른 사람들과 같은 형태를 취하니 '따르다'." },
    'consent': { example: "You need your parents' consent to go on the trip.", translation: "그 여행을 가려면 부모님의 동의가 필요하다.", mnemonic: "'콘센트(consent)' 꽂는 것을 '동의하다'." },
    'consequent': { example: "His long illness and the consequent loss of his job made him depressed.", translation: "그의 오랜 병과 그 결과로서 일어난 실직은 그를 우울하게 만들었다.", mnemonic: "'consequence(결과)'의 형용사형. '결과로서 일어나는'." },
    'considerable': { example: "The plan requires a considerable investment.", translation: "그 계획은 상당한 투자를 필요로 한다.", mnemonic: "'consider(고려하다)'할 만큼 양이나 정도가 '상당한'." },
    'constitute': { example: "Twelve months constitute a year.", translation: "12개월이 1년을 구성한다.", mnemonic: "'콘 스티커 투(constitute)'! 이 옥수수 스티커 두 개가 한 세트를 '구성한다'." },
    'constrain': { example: "She felt constrained to do what he wanted.", translation: "그녀는 그가 원하는 것을 하도록 강요받는다고 느꼈다.", mnemonic: "'큰 스트레인(constrain)'! 큰 긴장감을 주며 하도록 '강요하다'." },
    'construct': { example: "The company will construct a new office building.", translation: "그 회사는 새로운 사무용 건물을 건설할 것이다.", mnemonic: "'con(함께) + struct(세우다)' -> 함께 구조물을 세우니 '건설하다'." },
    'consult': { example: "You should consult a doctor about your symptoms.", translation: "당신의 증상에 대해 의사와 상담해야 합니다.", mnemonic: "'컨설턴트(consultant)'는 '상담해주는(consult)' 사람." },
    'consume': { example: "The average person consumes about 2,000 calories a day.", translation: "보통 사람은 하루에 약 2,000 칼로리를 소비한다.", mnemonic: "'컨슈머(consumer)'는 '소비하는' 사람." },
    'contemporary': { example: "He was a contemporary of Shakespeare.", translation: "그는 셰익스피어와 동시대 사람이었다.", mnemonic: "'con(함께) + tempo(시간)' -> 같은 시간대에 사니 '동시대의'." },
    'contradict': { example: "The evidence contradicts his testimony.", translation: "그 증거는 그의 증언과 모순된다(반박한다).", mnemonic: "'contra(반대) + dict(말하다)' -> 반대로 말하니 '반박하다'." },
    'contrary': { example: "Contrary to popular belief, the Earth is not flat.", translation: "통념과는 반대로, 지구는 평평하지 않다.", mnemonic: "'contra(반대)'에서 온 말. '반대의'." },
    'controversial': { example: "Abortion is a highly controversial issue.", translation: "낙태는 매우 논란이 되는 문제이다.", mnemonic: "'controversy(논란)'의 형용사형. '논란이 되는'." },
    'convene': { example: "The committee will convene at 10 a.m.", translation: "위원회는 오전 10시에 소집될 것이다.", mnemonic: "'con(함께) + vene(오다)' -> 함께 오게 하니 '소집하다'." },
    'converse': { example: "She enjoyed conversing with people from other cultures.", translation: "그녀는 다른 문화권의 사람들과 대화하는 것을 즐겼다.", mnemonic: "'conversation(대화)'은 '대화하는(converse)' 것." },
    'convert': { example: "The sofa converts into a bed.", translation: "그 소파는 침대로 전환된다.", mnemonic: "'컨버터(converter)'는 신호를 '전환하는' 장치." },
    'cooperate': { example: "The two countries agreed to cooperate on the project.", translation: "두 나라는 그 프로젝트에 협력하기로 합의했다.", mnemonic: "'co(함께) + operate(작동하다)' -> 함께 일하니 '협력하다'." },
    'coordinate': { example: "We need to coordinate our efforts to be successful.", translation: "성공하기 위해 우리는 우리의 노력을 조정할 필요가 있다.", mnemonic: "'코디네이터(coordinator)'는 일정을 '조정하는' 사람." },
    'core': { example: "The core of the problem is a lack of funding.", translation: "문제의 핵심은 자금 부족이다.", mnemonic: "사과의 '코어(core)' 부분! 가장 중요한 '핵심'." },
    'correspond': { example: "The numbers correspond to the locations on the map.", translation: "그 숫자들은 지도상의 위치와 일치한다.", mnemonic: "'cor(함께) + respond(응답하다)' -> 서로 똑같이 응답하니 '일치하다'." },
    'crucial': { example: "This exam is crucial for your future.", translation: "이 시험은 당신의 미래에 결정적으로 중요하다.", mnemonic: "'크루셜(crucial)'! '그릇이' 깨지느냐 마느냐의 '결정적인' 순간." },
    'currency': { example: "What is the local currency in Japan?", translation: "일본의 현지 통화는 무엇인가요?", mnemonic: "'current(현재의, 흐름)' -> 현재 유통되는 돈, '통화'." },
    'deduce': { example: "From his silence, I deduced that he was angry.", translation: "그의 침묵으로부터, 나는 그가 화났다고 추론했다.", mnemonic: "'de(아래로) + duce(이끌다)' -> 단서에서 결론을 아래로 이끌어내니 '추론하다'." },
    'demonstrate': { example: "The study demonstrates the link between smoking and cancer.", translation: "그 연구는 흡연과 암 사이의 연관성을 입증한다.", mnemonic: "'데모(demo)'는 제품의 성능을 '입증하는' 것." },
    'denote': { example: "A red triangle on the map denotes a historical site.", translation: "지도 위의 빨간 삼각형은 역사적인 장소를 나타낸다.", mnemonic: "'디 노트(de-note)'! 아래에 '노트' 필기해서 의미를 '나타내다'." },
    'derive': { example: "Many English words are derived from Latin.", translation: "많은 영어 단어들은 라틴어에서 유래했다.", mnemonic: "'드라이브(drive)'해서 강에서 물을 '끌어내다'." },
    'detect': { example: "This device can detect hidden cameras.", translation: "이 장치는 숨겨진 카메라를 감지할 수 있다.", mnemonic: "'디텍티브(detective-탐정)'는 단서를 '감지하는' 사람." },
    'deviate': { example: "He never deviates from his daily routine.", translation: "그는 그의 일상에서 결코 벗어나지 않는다.", mnemonic: "'de(이탈) + via(길)' -> 길에서 이탈하니 '벗어나다'." },
    'differentiate': { example: "It's difficult to differentiate between the two versions.", translation: "두 버전 사이를 구별하기는 어렵다.", mnemonic: "'different(다른)'에서 온 말. 다르게 만드니 '구별하다'." },
    'dimension': { example: "The problem has a social and a political dimension.", translation: "그 문제는 사회적 그리고 정치적 차원을 가지고 있다.", mnemonic: "3D 영화의 'D'는 '디멘션(dimension-차원)'." },
    'diminish': { example: "His influence has diminished over the years.", translation: "그의 영향력은 수년에 걸쳐 감소했다.", mnemonic: "'뒤'에 '미니(mini)' 사이즈로 만들어서 '감소시키다'." },
    'discrete': { example: "The process consists of several discrete steps.", translation: "그 과정은 몇 개의 별개의 단계로 이루어져 있다.", mnemonic: "'디스 크리트(this crete)'! 이 크레타 섬은 다른 섬과 '별개의' 섬이야." },
    'discriminate': { example: "It is illegal to discriminate against people based on their race.", translation: "인종을 근거로 사람들을 차별하는 것은 불법이다.", mnemonic: "'dis(떨어져) + criminate(가르다)' -> 따로 갈라놓으니 '차별하고, 구별하다'." },
    'dispose': { example: "Please dispose of your trash properly.", translation: "쓰레기를 적절하게 처리해 주세요.", mnemonic: "'디스 포즈(this pose)'! 이 포즈를 취하고 쓰레기를 '처리하다'." },
    'distinct': { example: "There is a distinct smell of gas in the room.", translation: "방에서 뚜렷한 가스 냄새가 난다.", mnemonic: "'디스 팅트(this tint)'! 이 틴트 색깔은 다른 것과 '뚜렷하게' 달라." },
    'distort': { example: "The media often distorts the truth.", translation: "언론은 종종 진실을 왜곡한다.", mnemonic: "'디스 토스트(this toast)'! 이 토스트는 모양이 '왜곡되어' 있네." },
    'distribute': { example: "They distributed flyers to every house.", translation: "그들은 모든 집에 전단지를 배포했다.", mnemonic: "'dis(멀리) + tribute(주다)' -> 멀리까지 나누어 주니 '배포하다'." },
    'diverse': { example: "The city has a diverse population.", translation: "그 도시는 다양한 인구를 가지고 있다.", mnemonic: "'다이버(diver)'들은 '다양한' 바다 생물을 만난다." },
    'document': { example: "It is important to document all your expenses.", translation: "모든 지출을 기록하는 것이 중요하다.", mnemonic: "'도큐먼트(document-문서)'는 사실을 '기록한' 것." },
    'domain': { example: "This problem is outside my domain of expertise.", translation: "이 문제는 제 전문 영역 밖입니다.", mnemonic: "'도메인(domain)' 주소는 인터넷 상의 나의 '영역'." },
    'domestic': { example: "The company focuses on the domestic market.", translation: "그 회사는 국내 시장에 집중한다.", mnemonic: "'도메스틱(domestic)'! '도'둑이 '메'고 '스틱'을 들고 '국내'를 활보하다. (재미로)" },
    'dominant': { example: "The company has a dominant position in the market.", translation: "그 회사는 시장에서 지배적인 위치를 차지하고 있다.", mnemonic: "'dominate(지배하다)'의 형용사형. '지배적인'." },
    'duration': { example: "The duration of the movie is two hours.", translation: "그 영화의 지속 기간은 2시간이다.", mnemonic: "'durable(내구성 있는)'은 '지속 기간'이 긴 것." },
    'dynamic': { example: "He is a dynamic and energetic leader.", translation: "그는 역동적이고 활기찬 지도자이다.", mnemonic: "'다이너마이트(dynamite)'처럼 폭발적이고 '역동적인'." },
    'eliminate': { example: "The new policy aims to eliminate poverty.", translation: "새로운 정책은 빈곤을 제거하는 것을 목표로 한다.", mnemonic: "'이리(eli) 미네(minate)'! 이리 와서 먼지를 '밀어서' '제거해'." },
    'empirical': { example: "The theory is based on empirical evidence.", translation: "그 이론은 경험에 의한 증거에 기반한다.", mnemonic: "'엠파이어(empire)'를 건설한 황제의 '경험에 의한' 통치." },
  },
  gre: {
    'abate': { example: "The storm's fury began to abate.", translation: "폭풍의 맹렬함이 잦아들기 시작했다.", mnemonic: "'어, 베이트(bait-미끼)'를 주니 화가 '줄어드네'." },
    'aberrant': { example: "His aberrant behavior raised concerns among his friends.", translation: "그의 비정상적인 행동은 친구들 사이에 우려를 낳았다.", mnemonic: "'에러(error)가 있는 개미(ant)'는 '비정상적'이지." },
    'abjure': { example: "He abjured his former beliefs under pressure.", translation: "그는 압력에 못 이겨 이전의 신념을 포기했다.", mnemonic: "'애, 부줘(abjure)'! 애를 부숴버리겠다고 협박해서 신념을 '포기하게' 만들다." },
    'abrogate': { example: "The treaty was abrogated by the new government.", translation: "그 조약은 새 정부에 의해 폐지되었다.", mnemonic: "'애, 불어 게이트(abrogate)'! 애가 불어버린 게이트는 쓸모없으니 '폐지해'." },
    'abstruse': { example: "The professor's lecture on quantum physics was abstruse.", translation: "양자 물리학에 대한 교수의 강의는 난해했다.", mnemonic: "'앱스(apps)를 트루(true)'로 만드는 건 '난해한' 코딩." },
    'accede': { example: "The management was forced to accede to the workers' demands.", translation: "경영진은 노동자들의 요구에 동의할 수밖에 없었다.", mnemonic: "'access(접근)'를 허락하며 '동의하다'." },
    'acerbic': { example: "He is known for his acerbic wit.", translation: "그는 신랄한 재치로 알려져 있다.", mnemonic: "'아, 써빅(acerbic)'! 맛이 너무 써서 '신랄한' 비판을 하다." },
    'acquiesce': { example: "She acquiesced in the decision, despite her misgivings.", translation: "그녀는 의구심에도 불구하고 그 결정에 묵인했다.", mnemonic: "'ac(향해) + quiet(조용한)' -> 조용히 따르며 '묵인하다'." },
    'adroit': { example: "He was an adroit negotiator.", translation: "그는 능숙한 협상가였다.", mnemonic: "'안드로이드(android)' 로봇처럼 모든 일에 '능숙한'." },
    'aesthete': { example: "He was a true aesthete, appreciating beauty in all its forms.", translation: "그는 모든 형태의 아름다움을 감상하는 진정한 심미가였다.", mnemonic: "'aesthetic(미학)'을 아는 사람, 즉 '심미안이 있는 사람'." },
    'alacrity': { example: "She accepted the invitation with alacrity.", translation: "그녀는 그 초대를 선뜻 받아들였다.", mnemonic: "'얼래, 크리티(alacrity)'컬! 크리티컬 공격을 '민첩하게' 피하다." },
    'amalgamate': { example: "The two companies will amalgamate next year.", translation: "그 두 회사는 내년에 합병할 것이다.", mnemonic: "'아, 말까메이트(amalgamate)'? 합칠까 말까 하다가 결국 '합병하다'." },
    'ameliorate': { example: "They are trying to ameliorate the living conditions of the poor.", translation: "그들은 가난한 사람들의 생활 환경을 개선하려고 노력하고 있다.", mnemonic: "'아, 밀리오레(ameliorate)'! 쇼핑몰을 리모델링해서 '개선하다'." },
    'anachronism': { example: "The sword in the modern movie was an anachronism.", translation: "현대 영화에 나온 그 칼은 시대착오적인 것이었다.", mnemonic: "'ana(거슬러) + chron(시간)' -> 시간을 거스르니 '시대착오'." },
    'anathema': { example: "Racial prejudice is an anathema to a civilized society.", translation: "인종적 편견은 문명 사회에서 절대 반대되는 것이다.", mnemonic: "'아, 나 때마(anathema)'! 아, 나를 때리다니! 너는 '저주받을' 놈이야!" },
    'anomalous': { example: "The anomalous test results required further investigation.", translation: "그 이례적인 실험 결과는 추가적인 조사를 필요로 했다.", mnemonic: "'a(not) + nomal(normal)' -> 정상이 아니니 '이례적인'." },
    'antipathy': { example: "He felt a strong antipathy towards his new boss.", translation: "그는 새로운 상사에게 강한 반감을 느꼈다.", mnemonic: "'anti(반대) + pathy(감정)' -> 반대하는 감정, 즉 '반감'." },
    'apocryphal': { example: "Most of the stories about him are apocryphal.", translation: "그에 대한 대부분의 이야기는 진위가 의심스럽다.", mnemonic: "'아포, 칼이 풀(apocryphal)'! 아파, 칼이 풀렸다고? 그 말 '진위가 의심스러운데'." },
    'approbation': { example: "The new policy received the approbation of the public.", translation: "그 새로운 정책은 대중의 승인을 받았다.", mnemonic: "'ap(향하여) + probation(증명)' -> 좋다고 증명되었으니 '승인, 칭찬'. (approve와 유사)" },
    'arcane': { example: "He was the only one who understood the arcane rules of the game.", translation: "그는 그 게임의 난해한 규칙을 이해하는 유일한 사람이었다.", mnemonic: "'아, 케인(arcane)'! 아벨을 죽인 카인의 이야기는 '비밀스럽고 난해하다'." },
    'ardor': { example: "He spoke with great ardor about his love for his country.", translation: "그는 조국에 대한 사랑을 큰 열정을 가지고 말했다.", mnemonic: "'아더(ardor)' 왕의 '열정'적인 리더십!" },
    'artifice': { example: "The whole story was just a clever artifice to deceive us.", translation: "그 모든 이야기는 단지 우리를 속이기 위한 교묘한 책략이었다.", mnemonic: "'art(예술) + fice(만들다)' -> 예술적으로 교묘하게 만들어낸 '책략, 기교'." },
    'asperity': { example: "She responded with asperity to the criticism.", translation: "그녀는 그 비판에 거칠게 반응했다.", mnemonic: "'아스파라거스(asparagus)'를 '티(tea)'에 넣어 마시라니, 너무 '가혹한' 요구야." },
    'assiduous': { example: "She was an assiduous student, always studying hard.", translation: "그녀는 항상 열심히 공부하는 부지런한 학생이었다.", mnemonic: "'애, 씨두었으(assiduous)'! 애가 밭에 씨를 '부지런히' 두었어." },
    'attenuate': { example: "The medicine will attenuate the symptoms of the fever.", translation: "그 약은 열의 증상을 약화시킬 것이다.", mnemonic: "'어, 테뉴에이트(attenuate)'! '어, 쟤 뉴(new) 에이트(eight)'! 새로 8살이 되더니 힘이 '약화되었네'." },
    'austere': { example: "The monks live an austere life in the monastery.", translation: "수도승들은 수도원에서 금욕적인 삶을 산다.", mnemonic: "'오, 스티어(austere)'! '오, 조종간(steer)'을 잡은 선장님은 매우 '엄격하다'." },
    'avarice': { example: "His heart was filled with avarice.", translation: "그의 마음은 탐욕으로 가득 찼다.", mnemonic: "'아, 바랬으(avarice)'! 아, 저것도 바라고 이것도 바라는 끝없는 '탐욕'." },
    'baleful': { example: "He gave me a baleful look.", translation: "그는 나에게 위협적인 눈초리를 보냈다.", mnemonic: "'베일(bale) 풀(ful)'! 건초더미가 가득한 곳은 화재에 '해롭고 위협적'이다." },
    'belie': { example: "His smile belied his true feelings.", translation: "그의 미소는 그의 진짜 감정과 모순되었다.", mnemonic: "'be + lie(거짓말)' -> 거짓말처럼 보이게 하니 '모순되다'." },
    'bellicose': { example: "The bellicose nation was always ready for war.", translation: "그 호전적인 국가는 항상 전쟁 준비가 되어 있었다.", mnemonic: "'벨리(belli-전쟁) 코스(cose)'! 전쟁 코스를 밟는 '호전적인' 성격." },
    'benignant': { example: "The benignant king was loved by his people.", translation: "그 친절한 왕은 백성들의 사랑을 받았다.", mnemonic: "'bene(좋은) + gnant' -> 좋은 성품을 가졌으니 '친절한, 유익한'." },
    'bombastic': { example: "His bombastic speech was full of empty promises.", translation: "그의 과장된 연설은 공허한 약속으로 가득했다.", mnemonic: "'밤(bomb) 같은' 말을 펑펑 터뜨리니 '과장된'." },
    'bucolic': { example: "She dreamed of a bucolic life in the countryside.", translation: "그녀는 시골에서의 전원적인 삶을 꿈꿨다.", mnemonic: "'뷰(view) 콜릭(colic)'! '전원적인' 풍경을 보니 마음이 아파(colic). (아름다워서)" },
    'cadge': { example: "He was always cadging money from his friends.", translation: "그는 항상 친구들에게 돈을 빌붙었다.", mnemonic: "'캐지(cadge)'? 주머니를 '캐서' 돈을 얻어내며 '빌붙다'." },
    'calumny': { example: "He was a victim of calumny.", translation: "그는 중상의 희생자였다.", mnemonic: "'칼럼(column)이' 나를 '비방하는' 내용으로 가득해." },
    'captious': { example: "The captious critic found fault with every detail.", translation: "그 트집 잡기 좋아하는 비평가는 모든 세부 사항에서 흠을 찾아냈다.", mnemonic: "'캡(cap) 셔스(tious)'! 모자(cap) 삐뚤어졌다고 '트집 잡는'." },
    'castigate': { example: "The coach castigated the team for their poor performance.", translation: "코치는 팀의 부진한 성적에 대해 혹평했다.", mnemonic: "'캐스트(cast-던지다) 게이트(gate)'! 성문 밖으로 던져버리며 '징계하다'." },
    'censure': { example: "The senator faced censure for his unethical behavior.", translation: "그 상원의원은 그의 비윤리적인 행동으로 비난에 직면했다.", mnemonic: "'센 척(censure)'하는 사람을 '비난하다'." },
    'chicanery': { example: "He used chicanery to win the election.", translation: "그는 선거에서 이기기 위해 속임수를 썼다.", mnemonic: "'시카고(Chicago)'의 악명 높은 '속임수'꾼 알 카포네." },
    'churlish': { example: "It would be churlish to refuse her invitation.", translation: "그녀의 초대를 거절하는 것은 무례한 일일 것이다.", mnemonic: "'철없는' 아이처럼 '무례하게' 굴다." },
    'cogent': { example: "She presented a cogent argument for her proposal.", translation: "그녀는 자신의 제안에 대해 설득력 있는 주장을 펼쳤다.", mnemonic: "'코, 젠틀(cogent)'! 코가 젠틀한 신사는 말이 '설득력 있다'." },
    'commensurate': { example: "Your salary will be commensurate with your experience.", translation: "당신의 급여는 당신의 경력에 비례할 것입니다.", mnemonic: "'커먼(common) 슐레이트(surate)'! 흔한 슬레이트 지붕은 가격도 그 가치에 '비례한다'." },
    'complaisant': { example: "He was a complaisant husband, always agreeing with his wife.", translation: "그는 항상 아내에게 동의하는, 선뜻 따르는 남편이었다.", mnemonic: "'컴(come), 플리즈(please)'! 이리 오라는 말에 '선뜻 따르는'." },
    'concomitant': { example: "Loss of memory is a natural concomitant of old age.", translation: "기억력 상실은 노년에 자연스럽게 수반되는 것이다.", mnemonic: "'컴(come) 밑은(mitant)'! 주된 현상 밑에 따라 '오는', 즉 '수반되는'." },
    'confound': { example: "The complex instructions confounded the students.", translation: "그 복잡한 설명서는 학생들을 혼동시켰다.", mnemonic: "'콘(con)을 파운드(found)'! 옥수수를 발견했는데 금인 줄 알고 '혼동하다'." },
    'connoisseur': { example: "He is a connoisseur of fine wines.", translation: "그는 고급 와인 감정가이다.", mnemonic: "'코너에 있는 슈(connoisseur)'! 저 구석에 있는 신발의 가치를 알아보는 '전문가'." },
    'consummate': { example: "He is a consummate artist.", translation: "그는 완전한 예술가이다.", mnemonic: "'콘서트 메이트(consummate)'! 나와 콘서트 메이트가 되어 공연을 '완벽하게 하다'." },
    'contrite': { example: "He was contrite after his angry outburst.", translation: "그는 화를 터뜨린 후 뉘우쳤다.", mnemonic: "'큰 트라이(try)'! 크게 잘못해서 다시 '시도하며' '뉘우치는'." },
    'contumacious': { example: "The contumacious student refused to obey the rules.", translation: "그 고집 센 학생은 규칙 따르기를 거부했다.", mnemonic: "'컨츄리 마우스(country mouse)'는 '고집이 세다'." },
    'copious': { example: "She took copious notes during the lecture.", translation: "그녀는 강의 중에 풍부한 필기를 했다.", mnemonic: "'코피(copi) 어스(ous)'! 코피가 우리에게 '풍부하게' 나다." },
    'corpulent': { example: "The corpulent man had difficulty climbing the stairs.", translation: "그 뚱뚱한 남자는 계단 오르기를 힘들어했다.", mnemonic: "'코끼리(corpulent)'처럼 '뚱뚱한'." },
    'cosset': { example: "She was cosseted and spoiled by her parents.", translation: "그녀는 부모 밑에서 응석받이로 자랐다.", mnemonic: "'코, 셋(cosset)'! 코가 셋 달린 아이를 너무 귀여워하며 '응석받이로 키우다'." },
    'craven': { example: "The craven soldier deserted his post.", translation: "그 비겁한 군인은 자신의 초소를 버렸다.", mnemonic: "'크, 내 입은(craven)'! 크, 내 입으로는 말 못 해... 라고 말하는 '비겁한' 사람." },
    'credulous': { example: "Credulous people are easily tricked by scams.", translation: "잘 속는 사람들은 사기에 쉽게 넘어간다.", mnemonic: "'크레딧(credit-신용)'을 너무 쉽게 줘서 '잘 속는'." },
    'cursory': { example: "He gave the report a cursory glance.", translation: "그는 보고서를 대충 훑어보았다.", mnemonic: "마우스 '커서(cursor)'를 휙휙 움직이며 '대충 하는' 검토." },
    'dearth': { example: "There is a dearth of evidence to support his claim.", translation: "그의 주장을 뒷받침할 증거가 부족하다.", mnemonic: "'더 쓰(dearth)'고 싶은데 잉크가 '부족'하네." },
    'debacle': { example: "The project ended in a complete debacle.", translation: "그 프로젝트는 완전한 대실패로 끝났다.", mnemonic: "'뒤바뀌클(debacle)'! 모든 것이 뒤바뀌어버린 '대실패'." },
    'decorum': { example: "He behaved with the utmost decorum at the formal dinner.", translation: "그는 공식 만찬에서 최대한의 예의를 갖춰 행동했다.", mnemonic: "'데코(deco)를 룸(room)'에 할 때도 '예의'를 지켜야 해." },
    'deference': { example: "He showed deference to his elders.", translation: "그는 어른들에게 존중을 표했다.", mnemonic: "'디퍼런스(difference)'를 인정하고 '존중'하는 태도." },
    'deleterious': { example: "Smoking has deleterious effects on your health.", translation: "흡연은 건강에 해로운 영향을 미친다.", mnemonic: "'딜리트(delete)'해버리고 싶을 만큼 '해로운'." },
    'demagogue': { example: "The demagogue manipulated the emotions of the crowd.", translation: "그 선동 정치가는 군중의 감정을 조종했다.", mnemonic: "'데모(demo)'를 이끄는 '아귀(gogue)' 같은 '선동 정치가'." },
    'demur': { example: "She demurred at the suggestion, saying it was too risky.", translation: "그녀는 너무 위험하다며 그 제안에 이의를 제기했다.", mnemonic: "'뒤에 머(demur)'물러서서 '이의를 제기하다'." },
    'denigrate': { example: "He likes to denigrate the achievements of others.", translation: "그는 다른 사람들의 업적을 폄하하기를 좋아한다.", mnemonic: "'뒤에서 네(de-ni)가 그래(grate)'? 뒤에서 남을 깎아내리며 '폄하하다'." },
    'deride': { example: "His crazy ideas were derided by everyone.", translation: "그의 황당한 아이디어는 모든 사람에게 조롱당했다.", mnemonic: "'뒤(de)에서 라이드(ride)'! 뒤에서 말 타는 시늉을 하며 '조롱하다'." },
    'desultory': { example: "He made a few desultory attempts to clean the room.", translation: "그는 방을 청소하려는 몇 번의 산만한 시도를 했다.", mnemonic: "'디스(this) 스토리(story)'는 너무 '두서없어'." },
    'diaphanous': { example: "The bride wore a diaphanous veil.", translation: "신부는 아주 얇은 베일을 썼다.", mnemonic: "'다이아(dia) 빼놨으(phanous)'! 다이아가 다 '비치는' '아주 얇은' 천." },
    'didactic': { example: "The story was didactic, intended to teach a moral lesson.", translation: "그 이야기는 도덕적 교훈을 주기 위한 의도를 가진, 교훈적인 것이었다.", mnemonic: "'디댁틱(didactic)'! '디'지털 시대에도 '댁'의 말씀은 '교훈적'입니다." },
    'diffident': { example: "She was diffident about expressing her opinions.", translation: "그녀는 자신의 의견을 표현하는 데 소심했다.", mnemonic: "'디피컬트(difficult)'한 문제 앞에서 '자신 없어' 하는 '소심한' 모습." },
    'dilatory': { example: "He is always dilatory in paying his bills.", translation: "그는 항상 고지서 대금을 지연하여 지불한다.", mnemonic: "'딜레이(delay)'를 일으키는 '지연하는' 태도." },
    'disabuse': { example: "Let me disabuse you of that foolish notion.", translation: "당신의 그 어리석은 생각에 대한 오해를 바로잡아 주겠습니다.", mnemonic: "'dis(반대) + abuse(오용)' -> 잘못 사용된 생각을 반대로 돌려 '오해를 바로잡다'." },
    'discomfit': { example: "He was discomfited by the unexpected question.", translation: "그는 예상치 못한 질문에 당황했다.", mnemonic: "'디스(this) 컴(come) 핏(fit)'! 이 옷이 안 맞아서(fit) '당황하다'." },
    'disparate': { example: "The two cultures are disparate in many ways.", translation: "그 두 문화는 여러 면에서 본질적으로 다르다.", mnemonic: "'디스(this) 퍼레이트(parate)'! 이 퍼레이드는 저번과 '본질적으로 달라'." },
    'dissemble': { example: "She dissembled her true feelings behind a smile.", translation: "그녀는 미소 뒤에 자신의 진짜 감정을 숨겼다.", mnemonic: "'디스(this) 셈블(semble-~처럼 보이다)'! 이것처럼 보이게 꾸미며 진짜 모습을 '숨기다'." },
    'dissonance': { example: "There was a dissonance between his words and his actions.", translation: "그의 말과 행동 사이에는 불일치가 있었다.", mnemonic: "'디스(dis-반대) + sonance(소리)' -> 서로 다른 소리가 나니 '부조화'." },
    'distend': { example: "The balloon distended to the point of bursting.", translation: "풍선은 터지기 직전까지 부풀어 올랐다.", mnemonic: "'디스(this) 텐트(tend)'! 이 텐트는 바람에 '부풀어' 오른다." },
    'divest': { example: "The king was divested of all his power.", translation: "왕은 그의 모든 권력을 박탈당했다.", mnemonic: "'다(di) 베스트(vest)'! 조끼(vest)까지 다 벗겨서 '빼앗다'." },
    'dogmatic': { example: "He is a dogmatic person, unwilling to consider other views.", translation: "그는 다른 견해를 고려하려 하지 않는 독단적인 사람이다.", mnemonic: "'도그(dog) 마틱(matic)'! 개처럼 자기주장만 짖어대는 '독단적인' 태도." },
    'duress': { example: "He signed the confession under duress.", translation: "그는 협박에 못 이겨 자백서에 서명했다.", mnemonic: "'듀레스(duress)'! '둘'이서 '스트레스'를 주며 '협박'하다." },
    'ebullient': { example: "She was in an ebullient mood after winning the prize.", translation: "그녀는 상을 받은 후 열정적인 기분이었다.", mnemonic: "'이, 불리언트(ebullient)'! 이 불리언(boolean) 연산에 대한 그의 설명은 '열정적'이야." },
    'effrontery': { example: "He had the effrontery to ask for a raise after only a week.", translation: "그는 고작 일주일 만에 월급 인상을 요구하는 뻔뻔스러움을 보였다.", mnemonic: "'에, 프론트(front)에서' 그렇게 행동하다니, '뻔뻔하네'." },
    'egregious': { example: "It was an egregious error.", translation: "그것은 지독한 실수였다.", mnemonic: "'이, 그리 지었으(egregious)'! 이걸 이렇게 '지독하게' 지었다니!" },
    'elegiac': { example: "The poem has an elegiac tone.", translation: "그 시는 애가의 분위기를 띤다.", mnemonic: "'엘레지(elegy)'가 '슬픈' 노래, 즉 '애가'." },
    'elicit': { example: "The lawyer tried to elicit the truth from the witness.", translation: "변호사는 증인으로부터 진실을 끌어내려고 노력했다.", mnemonic: "'일리(eli) 있는 시트(cit)'! 일리 있는 답변을 '끌어내다'." },
    'emollient': { example: "She used an emollient cream for her dry skin.", translation: "그녀는 건성 피부를 위해 완화 크림을 사용했다.", mnemonic: "'이, 몰리언트(emollient)'! '이'리 와서 '몰'래 '연고' 발라줄게. 피부를 '진정시키는' 연고." },
    'enervate': { example: "The long journey enervated the travelers.", translation: "긴 여행은 여행자들의 기력을 약화시켰다.", mnemonic: "'에너(ener)지를 베이트(vate)'! 에너지를 베어버리니 '약화시키다'." },
    'engender': { example: "The issue has engendered a lot of debate.", translation: "그 문제는 많은 논쟁을 낳았다.", mnemonic: "'인(in) 젠더(gender)'! 성별 안에서 아이를 '낳다'." },
    'ennui': { example: "He suffered from a sense of ennui and boredom.", translation: "그는 권태감과 지루함으로 고통받았다.", mnemonic: "'앙, 뉘(ennui)'! 앙, 하고 누워만 있으니 '권태'롭다." },
    'enshrine': { example: "The memory was enshrined in his heart forever.", translation: "그 기억은 그의 마음속에 영원히 신성하게 보관되었다.", mnemonic: "'en(안에) + shrine(성지)' -> 성지 안에 모시니 '신성하게 보관하다'." },
    'ephemeral': { example: "Fame is ephemeral.", translation: "명성은 단명한다.", mnemonic: "'이, 피 머를(ephemeral)'! 이마에 핀 머리카락은 '단명하는' 운명. (짧게 있다가 빠지니까)" },
    'epicure': { example: "He is an epicure who loves to try new restaurants.", translation: "그는 새로운 식당을 시도하기를 좋아하는 미식가이다.", mnemonic: "'에피(epi)타이저부터 큐(cure)'어까지 완벽해야 만족하는 '미식가'." },
    'equanimity': { example: "He faced the crisis with equanimity.", translation: "그는 위기에 침착하게 맞섰다.", mnemonic: "'이퀄(equal) + 애니멀(animal)'! 어떤 동물 앞에서도 평등하게 '침착'함을 유지." },
    'equivocate': { example: "Stop equivocating and give me a straight answer.", translation: "얼버무리지 말고 확실한 대답을 주세요.", mnemonic: "'이퀴(equi-같은) 보케이트(vocate-목소리)'! 이쪽에도 저쪽에도 같은 목소리를 내며 '얼버무리다'." },
    'erudite': { example: "He is an erudite scholar.", translation: "그는 박식한 학자이다.", mnemonic: "'에루(e-밖으로) 다이트(dite-말하다)'! 아는 것을 밖으로 다 말할 수 있을 만큼 '박식한'." },
    'eschew': { example: "He eschews all forms of violence.", translation: "그는 모든 형태의 폭력을 피한다.", mnemonic: "'에취(eschew)'! 재채기하듯 '피하다'." },
    'espouse': { example: "He espoused the cause of the poor.", translation: "그는 가난한 사람들의 대의를 지지했다.", mnemonic: "내 '배우자(spouse)'를 '지지하다'." },
    'estimable': { example: "She has an estimable reputation as a scientist.", translation: "그녀는 과학자로서 존경할 만한 명성을 가지고 있다.", mnemonic: "'esteem(존경)' + 'able(가능한)' -> '존경할 만한'." },
    'eulogize': { example: "The speaker eulogized the brave soldiers.", translation: "연사는 용감한 군인들을 찬양했다.", mnemonic: "'율로지(eulogy-찬사)'! 율동과 노래로 '찬양하다'." },
    'exacerbate': { example: "His harsh words only exacerbated the situation.", translation: "그의 거친 말은 상황을 악화시킬 뿐이었다.", mnemonic: "'이그, 재수없어 베이트(exacerbate)'! 재수 없는 미끼를 던져 상황을 '악화시키다'." },
    'excoriate': { example: "The critic excoriated the new movie.", translation: "그 비평가는 새 영화를 혹평했다.", mnemonic: "'엑스(ex) 코리아(korea) 티(te)'! 전 한국 대표팀을 '혹평하다'." },
    'exigent': { example: "The exigent circumstances required immediate action.", translation: "그 긴급한 상황은 즉각적인 조치를 필요로 했다.", mnemonic: "'엑시트(exit) 젠틀(gentle)'! 비상구(exit)로 젠틀하게 나가야 하는 '긴급한' 상황." },
  }
};
